[build-system]
requires = ["poetry-core", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "SciPhi"
version = "0.1.0"
description = "SciPhi: A framework for breaking scaling laws."
authors = ["Owen Colegrove <owen@emergentagi.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
# Required dependencies
numpy = "^1.26.0"
python = ">=3.10,<3.12"
python-dotenv = "^1.0.0"
pandas = "^2.1.0"
# Begin optional dependencies
accelerate = { version = "^0.23.0", optional = true }
anthropic = { version = "^0.3.10", optional = true }
datasets = { version = "^2.14.5", optional = true }
openai = { version = "0.27.8", optional = true }
torch = { version = "^2.0.1", optional = true }
transformers = { version = "^4.33.1", optional = true }
vllm = { version = "0.1.7", optional = true }

[tool.poetry.extras]
anthropic_support = ["anthropic"]
hf_support = ["accelerate", "datasets", "torch", "transformers"]
openai_support = ["openai"]
vllm_support = ["accelerate", "torch", "vllm"]

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "6.1.0"
isort = "5.12.0"
pre-commit = "^3.3.3"
mypy = "^1.5.1"
sourcery = "^1.6.0"
types-requests = "^2.31.0.2"
types-attrs = "^19.1.0"
yapf = "0.40.1"

[tool.black]
line-length = 79

[tool.mypy]
ignore_missing_imports = true
exclude = 'zero_shot_replication/evals/leetcode_hard_gym'

[tool.flake8]
ignore = ["E501", "W503"]
exclude = 'zero_shot_replication/evals/leetcode_hard_gym'

