textbook:
  Water and Sanitation Infrastructure in Developing Countries: A Comprehensive Guide
  chapters:
    - Introduction to water and sanitation development:
        sections:
        - Basic concepts
        - Water rich / water poor
        - Pictoral tour of global water and sanitation
        subsections:
        - Importance of water and sanitation in developing countries
        - Challenges and barriers in water and sanitation development
    - Water, sanitation and hygiene-related diseases:
        sections:
        - Sources of water
        - Water supply planning
        subsections:
        - Waterborne diseases and their impact on public health
        - Sanitation-related diseases and their prevention
        - Hygiene practices and their role in disease prevention
    - Water quality and simple water quality field testing demo:
        sections:
        - Decentralized household water treatment
        - Safe storage
        subsections:
        - Water quality parameters and their significance
        - Methods of decentralized household water treatment
        - Importance of safe storage in maintaining water quality
        - Demonstration of simple water quality field testing techniques
    - Sanitation history, centralized wastewater treatment, and reuse:
        sections:
        - Sanitation history
        - Centralized wastewater treatment
        - Reuse
        subsections:
        - Evolution of sanitation practices throughout history
        - Overview of centralized wastewater treatment systems
        - Reuse of treated wastewater for irrigation and other purposes
        - Challenges and benefits of wastewater reuse
    - Wrap-up:
        sections:
        - Summary and conclusion
        subsections:
        - Key takeaways from the course
        - Future directions in water and sanitation infrastructure in developing countries