textbook:
  International Environmental Negotiation:
    chapters:
      - Treaty-making:
          sections:
          - Introduction, and global environmental treaty-making: How should we judge the outcomes?
            subsections:
            - Understanding global environmental challenges
            - Evaluating the effectiveness of global environmental treaties
          - The politics: North-South relations, role of civil society; role of international business interests
            subsections:
            - Power dynamics in international environmental negotiations
            - The role of civil society in shaping environmental treaties
            - Influence of international business interests on treaty-making
          - The negotiations: Multi-party negotiations and the problems of treaty enforcement
            subsections:
            - Challenges of multi-party negotiations in environmental diplomacy
            - Ensuring compliance and enforcement of environmental treaties
          - The science: What role for science and scientists?
            subsections:
            - Role of science in informing environmental negotiations
            - Incorporating scientific knowledge into policy-making
          - Simulation activity: The chlorine game
            subsections:
            - Understanding negotiation dynamics through a simulation game
            - Analyzing outcomes and strategies in the chlorine game
      - Copenhagen evaluations:
          sections:
          - Short student presentations
          - Presentations
          - Status of the Cancun round negotiations
      - Remaining student presentations/concluding discussions/last possible day to hand in final papers/class dinner:
          sections:
          - None specified
      - Response papers:
          sections:
          - Response paper 1 due
          - Response paper 2 due
      - Assignments:
          sections:
          - The following outlines due dates and descriptions for the assignments. Students will write a short memorandum (i.e., no more than three typed pages) commenting on the assigned readings for the week. Each of these response papers is worth a maximum of 10 points toward the final grade. Students will play The Chlorine Game in assigned groups of 12 outside of class. Each student will be required to post a two-page essay analyzing what happened in their play of the game and respond to an assigned set of questions.
      - Calendar:
          sections:
          - 'WEEK #TOPICS KEY DATES Treaty-making'
          - 'Introduction, and global environmental treaty-making: How should we judge the outcomes? (Susskind)'
          - 'The politics: North-South relations, role of civil society; role of international business interests (Susskind)'
          - Response paper 1 due
          - 'The negotiations: Multi-party negotiations and the problems of treaty enforcement (Susskind)'
          - 'The science: What role for science and scientists? (Moomaw)'
          - Response paper 2 due
          - 'Simulation activity: The chlorine game'
          - Copenhagen evaluations - short student presentations
          - Copenhagen evaluations – presentations
          - Status of the Cancun round negotiations
          - Remaining student presentations/concluding discussions/last possible day to hand in final papers/class dinner
      - Key dates:
          sections:
          - None specified
      - Lecture notes:
          sections:
          - None specified
      - Readings:
          sections:
          - None specified
      - Recitations:
          sections:
          - None specified
      - Exams:
          sections:
          - None specified
      - Syllabus:
          sections:
          - 30 points
          - 15 points
          - 10 points
          - 10 points
          - 15 points
          - 35 points
      - Projects:
          sections:
          - None specified