textbook:
  Regional Energy-Environmental Economic Modeling: A Comprehensive Guide

chapters:
  - Overview of regional sustainable development issues:
    sections:
      - Sustainable energy and environmental systems
        subsections: []

  - Green accounting and relevance for regional modeling:
    sections:
      - Green accounting
        subsections: []

  - Life-cycle assessments:
    sections:
      - Part 1
        subsections: []
      - Part 2
        subsections: []

  - Regional energy-efficiency and environmental models:
    sections:
      - Part 1
        subsections: []
      - Part 2
        subsections: []

  - Climate change models:
    sections:
      - Part 1
        subsections: []
      - Part 2
        subsections: []

  - Linkage between environmental and energy models:
    sections:
      - Part 1
        subsections: []
      - Part 2
        subsections: []

  - Student presentations:
    sections: []
    subsections: []