textbook:
  'Urban Design Skills: Observing, Interpreting, and Representing the City':
    chapters:
      - 'Chapter 1: Part I: Observing the City':
          sections:
            - 'Section 1.1: Introduction'
            - 'Section 1.2: Walk - East Cambridge/Kendall'
            - 'Section 1.3: A Methodology For Physical Analysis'
            - 'Section 1.4: Walk - South End/Back Bay'
            - 'Section 1.5: Freehand Sketching and Drawing Types I'
            - 'Section 1.6: Walk - Fens/Muddy River'
            - 'Section 1.7: Freehand Sketching and Drawing Types II'
            - 'Section 1.8: In Class Presentation'
            - 'Section 1.9: Rendering By Hand'
            - 'Section 1.10: Walk - Alewife'
      - 'Chapter 2: Part II: Fundamentals of Design':
          sections:
            - 'Section 2.1: Fundamentals of Line Drawings I'
            - 'Section 2.2: Walk - Cambridgeport'
            - 'Section 2.3: Fundamentals of Digital Work'
            - 'Section 2.4: Walk - Suburbs'
            - 'Section 2.5: Fundamentals of Digital Work II'
            - 'Section 2.6: Review Assignment Two'
            - 'Section 2.7: Models'
            - 'Section 2.8: Walk - Final Project Site'
            - 'Section 2.9: Perspective Basics'
            - 'Section 2.10: Presentations - Case Studies'
            - 'Section 2.11: Graphic Presentations'
            - 'Section 2.12: Laying Out Final Panels'
      - 'Chapter 3: Part III: Project Work':
          sections:
            - 'Section 3.1: Work Day'
            - 'Section 3.2: Final Review'