textbook:
  Materials for Biomedical Applications: A Comprehensive Guide
  chapters:
    - Introduction to Biomaterials:
        sections:
        - Biomaterials Defined
        - Structural Hierarchy in Materials and Biology
        subsections: []
    - Biomaterials Surfaces:
        sections:
        - Physics
        - Chemistry
        subsections: []
    - Protein-Surface Interactions:
        sections:
        - Protein-Surface Interactions (x2)
        subsections: []
    - Cell-Surface Interactions:
        sections:
        - Host Response to Biomaterials (x2)
        subsections: []
    - Surface Modification Methods:
        sections:
        - Surface Modification Methods (x2)
        subsections: []
    - Surface Characterization:
        sections:
        - Surface Characterization In situ
        subsections: []
    - Quantifying Cell Behavior:
        sections:
        - Quantifying Cell Behavior (x2)
        subsections: []
    - Statistical Analysis:
        sections:
        - Statistical Analysis
        subsections: []
    - Biosensors and Diagnostic Devices:
        sections:
        - Biosensors and Diagnostic Devices
        subsections: []
    - 'Drug Delivery: Controlled Release':
        sections:
        - 'Drug Delivery: Controlled Release (x3)'
        subsections: []
    - Biomaterials for Organ Replacement:
        sections:
        - Biomaterials for Organ Replacement
        subsections: []
    - Tissue Engineering:
        sections:
        - Tissue Engineering (x2)
        subsections: []
    - FDA Regulatory Issues and Course Evaluations:
        sections:
        - FDA Regulatory Issues and Course Evaluations
        subsections: []