textbook:
  Brownfields Policy and Practice: A Comprehensive Guide to Urban Redevelopment

chapters:
  - Introduction:
    - Course Overview
    - About the Authors
    - How to Use This Textbook
  - Chapter 1: Understanding Brownfields Basics
    - Section 1.1: The Urban Environment: Brownfield and Sprawl
    - Section 1.2: Brownfield Redevelopment and Transportation Policy
  - Chapter 2: Historical Context and Legal Framework
    - Section 2.1: How We Got Here: Law and Liability
  - Chapter 3: Market Forces and Opportunity Drivers
    - Section 3.1: Market Forces Influencing Brownfields Redevelopment
  - Chapter 4: Site Tour: City of Lynn
  - Chapter 5: Environmental Justice and Equity
    - Section 5.1: Environmental Justice: The View through the Chain Link Fence
  - Chapter 6: Environmental Constraints and Cleanup Technologies
    - Section 6.1: Overview of Environmental Constraints
    - Section 6.2: Guest Speaker - John McTigue, L.S.P.
    - Section 6.3: Environmental Constraints: Risk Assessments
    - Section 6.4: Guest Speaker - Dave Merill
  - Chapter 7: Recap of Environmental Issues
  - Chapter 8: Economic Considerations in Brownfields Redevelopment
  - Chapter 9: Liability and Risk Management
  - Chapter 10: Bringing it All Together
  - Chapter 11: Where does that Leave us?
  - Chapter 12: Case Study - Part II
  - Chapter 13: Case Study - Part III
  - Chapter 14: Student Presentations - I
  - Chapter 15: Student Presentations - II
  - Chapter 16: Student Presentations - III