textbook:
  'Photography as Inquiry: Exploring Landscape Through Visual Storytelling':
    chapters:
      - chapter_title: 'Introduction: Sensing Place'
        sections:
          - section_title: 'Chapter Overview'
          - section_title: 'Understanding Landscape Photography'
          - section_title: 'Importance of Visual Storytelling'
      - chapter_title: 'Reading and Telling Landscape'
        sections:
          - section_title: 'Lights of Day, in Season, in Place I'
            subsections:
              - subsection_title: 'Exploring Different Lighting Conditions'
              - subsection_title: 'Capturing Seasonal Changes in a Landscape'
              - subsection_title: 'Photographing the Essence of a Place'
          - section_title: 'Lights of Day, in Season, in Place II'
            subsections:
              - subsection_title: 'Advanced Techniques for Capturing Lighting'
              - subsection_title: 'Creating Visual Narratives through Seasonal Changes'
      - chapter_title: 'Workshop on Photoshop and Web Authoring'
        sections:
          - section_title: 'Significant Detail I: Elements of Landscape Language in the Context of Place'
            subsections:
              - subsection_title: 'Understanding Elements of Landscape Language'
              - subsection_title: 'Analyzing the Relationship between Elements and Place'
          - section_title: 'Significant Detail II'
            subsections:
              - subsection_title: 'Exploring the Power of Detail in Landscape Photography'
              - subsection_title: 'Creating Emotive Responses through Detailed Shots'
              - subsection_title: 'Enhancing Visual Impact through Detail-focused Editing'
      - chapter_title: 'Landscape Poetics'
        sections:
          - section_title: 'Landscape Poetics I'
            subsections:
              - subsection_title: 'Exploring the Emotional Language of Landscapes'
              - subsection_title: 'Capturing the Essence of a Place through Poetry'
              - subsection_title: 'Creating Visual Poems with Landscape Photography'
          - section_title: 'Landscape Poetics II'
            subsections:
              - subsection_title: 'Analyzing the Symbolism in Landscape Photography'
              - subsection_title: 'Expressing Personal Interpretations through Symbolic Imagery'
              - subsection_title: 'Creating Evocative Visual Narratives through Symbolic Elements'
      - chapter_title: 'Landscape Narratives'
        sections:
          - section_title: 'Landscape Narratives I: Singles, Pairs, Series, and Sequences'
            subsections:
              - subsection_title: 'Exploring Different Approaches to Landscape Narratives'
              - subsection_title: 'Crafting Compelling Visual Stories through Singles and Pairs'
              - subsection_title: 'Creating Sequential Narratives with Series and Sequences'
      - chapter_title: 'Storytelling: Words and Images'
        sections:
          - section_title: 'Review of Photo Essays in Online Galleries'
            subsections:
              - subsection_title: 'Analyzing and Critiquing Photo Essays'
              - subsection_title: 'Understanding the Power of Visual Storytelling in Photo Essays'
          - section_title: 'Photography as Inquiry'
            subsections:
              - subsection_title: 'Exploring the Intersection of Photography and Inquiry'
              - subsection_title: 'Using Photography as a Tool for Investigating Place'
              - subsection_title: 'Documenting and Communicating Findings through Visual Inquiry'