```yaml
course:
  textbook: "Comprehensive Guide to Beijing Urban Design"
  chapters:
    - Introduction to Urban Design:
        sections:
        - History of Urban Design
        - Principles of Urban Design
        - Role of Urban Design in Society
    - Urban Planning and Development:
        sections:
        - Urban Planning Process
        - Land Use and Zoning
        - Transportation Planning
        - Sustainability in Urban Design
        - Smart Cities
    - Urban Design Theory:
        sections:
        - Design Principles and Concepts
        - Human Scale and Proportion
        - Public Space Design
        - Urban Form and Morphology
        - Contextual Design
    - Urban Design Methods and Tools:
        sections:
        - Site Analysis and Evaluation
        - Urban Design Guidelines
        - Visualization Techniques
        - Computer-Aided Design (CAD)
        - Geographic Information Systems (GIS)
        - Virtual Reality in Urban Design
        - Augmented Reality in Urban Design
        - Building Information Modeling (BIM)
        - Drone Technology in Urban Design
    - Urban Design and Social Issues:
        sections:
        - Community Engagement
        - Social Equity in Urban Design
        - Affordable Housing
        - Historic Preservation
        - Cultural Identity in Urban Design
        - Inclusive Design for People with Disabilities
    - Sustainable Urban Design:
        sections:
        - Green Infrastructure
        - Energy Efficiency
        - Water Management
        - Waste Management
        - Urban Agriculture
        - Resilient Design for Climate Change
        - Circular Economy in Urban Design
    - Urban Design Case Studies:
        sections:
        - Successful Urban Design Projects
        - Urban Design Failures and Lessons Learned
        - International Urban Design Examples
        - Adaptive Reuse and Revitalization
        - Public Health and Well-being in Urban Design
        - Future Trends in Urban Design
    - Urban Design and Transportation:
        sections:
        - Pedestrian-Friendly Design
        - Transit-Oriented Development
        - Bicycle Infrastructure
        - Parking Design and Management
        - Complete Streets
        - Autonomous Vehicles in Urban Design
        - E-mobility and Urban Design
    - Urban Design and Technology:
        sections:
        - Digital Urban Design Tools
        - Building Information Modeling (BIM)
        - Augmented Reality in Urban Design
        - Virtual Reality in Urban Design
        - Internet of Things (IoT) in Urban Design
        - Artificial Intelligence in Urban Design
        - Blockchain Technology in Urban Design
```
```