textbook:
  Planning for Sustainable Development: A Comprehensive Guide
  chapters:
    - 'Chapter 1: Framing Sustainability: Global Problems and Local Actions':
        sections:
        - 'Section 1.1: Introduction and Overview'
        - 'Section 1.2: Some Prominent Ways of Framing Sustainability'
        - 'Section 1.3: Framing Sustainability Locally: An International Comparison'
    - 'Chapter 2: Understanding and Managing Change in Organizational Settings':
        sections:
        - 'Section 2.1: Sustainability and Innovation'
        - 'Section 2.2: Promoting Sustainability in State and Local Government'
        - 'Section 2.3: Sustainable Action at a University'
    - 'Chapter 3: Preliminary Presentations and In-class Critique':
        sections:
        - 'Section 3.1: Building a Story about Change'
        - 'Section 3.2: Working Session'
        - 'Section 3.3: Final Presentations'