```yaml
course:
  Electromagnetics and Applications:
    textbook:
      title: Electromagnetics: Theory and Applications
      chapters:
      - Review of Vector and Integral Calculus:
          sections:
          - Cartesian Coordinate System
          - Cylindrical Coordinate System
          - Spherical Coordinate System
          - Complex Notation
          - Gradient, Curl, and Divergence
      - Gauss’ and Ampere’s Laws:
          sections:
          - Superposition
          - Integral Forms
          - Volume Charge Density
          - Volume Current Density
      - Boundary Conditions:
          sections:
          - Derivation
          - Surface Charge Problems
          - Surface Current Problems
          - Perfectly Conducting Sphere or Cylinder
      - Maxwell’s Equations in Differential Form:
          sections:
          - Surface and Volume Charged Layers
          - Current Carrying Planar Layer
          - Cylinder and Sphere
      - Electric Field and Potential:
          sections:
          - Poisson’s and Laplace’s Equations
          - Potential of Point Charge
          - Coulomb Superposition Integral
      - Electric Dipole:
          sections:
          - Method of Images
          - Plane, Cylinder, and Sphere Problems
      - Conservation of Charge:
          sections:
          - Maxwell Capacitor
          - Magnetic Dipoles and Circuits
          - Reluctance
      - Wave Equation and Poynting’s Theorem:
          sections:
          - Oblique Incidence on Perfect Conductor
          - Transverse Magnetic
      - Lasers and Optics:
          sections:
          - Polarization by Reflection
          - Totally Reflecting Prisms
          - Fiber Optics
      - Transmission Line Sinusoidal Problems:
          sections:
          - Short Circuit, Open Circuit, and Loaded Ends
          - Approximations to Capacitors and Inductors
      - Impedance and VSWR Problems:
          sections:
          - Smith Chart
          - Single-stub Tuner
      - Reflections and Driven Problems:
          sections:
          - Reflections from Ends
          - Driven and Initial Value Problems
      - Rectangular Waveguides:
          sections:
          - TM and TE Modes
          - Cut-off
      - Cavity Resonators and Lasers:
          sections:
          - Group and Phase Velocity
          - Dispersion Relations
          - Torque-speed Characteristics
      - Force Problems in Capacitive and Inductive Systems:
          sections:
          - Force Problems
          - Capacitive Systems
          - Inductive Systems
      - Ohm’s Law and Faraday’s Disk:
          sections:
          - Ohm’s Law for Moving Media
          - Faraday’s Disk
      - Radiation by Charges and Currents:
          sections:
          - Setting the Gauge
          - Lorentz Gauge
          - Superposition Integral Solutions
      - Electric and Magnetic Fields from a Point Electric Dipole:
          sections:
          - Far-Field Solution
          - Radiation Resistance
          - Effective Dipole Length
          - Antenna Gain
      - Transmitting and Receiving Antennas:
          sections:
          - Wireless and Optical Communications
      - Acoustic Waves:
          sections:
          - Acoustic Waves
          - Acoustic Wave Boundary Value Problems
      - Course Review:
          sections:
          - Review of Topics
```