textbook:
  'Revitalizing Urban Main Streets: Strategies for Mission Hill & Egleston Square, Boston':
    chapters:
      - Introduction and Overview:
          sections:
            - 'Urban Neighborhood Decline: Causes, Consequences, Challenges'
            - Introduction to Main Street Sites/Issues
      - Revitalization Strategies I and II:
          sections:
            - Project Discussion
            - 'Economic Planning Tools II: Retail Market Analysis and Economic Planning'
            - 'Physical Design Tools II: Streetscape'
            - 'Economic Planning Tools III: Asset and Capacity Assessment'
            - 'Physical Design Tools III: Image and Neighborhood Form'
            - Egleston Square Team Presentation
            - Mission Hill Team Presentation
      - Synthesis:
          sections:
            - In-class Work - Proposals for moving forward
            - Client Presentations
      - Policies and Interventions:
          sections:
            - Marketing and Promotion
            - Business Development, Retention, and Attraction
            - Development
            - Transit-Oriented Development
            - Design and Zoning Guidelines
            - Safety and Sanitation
            - Organization and Capacity Building
      - Presentation of Draft Plans:
          sections:
            - Presentation of Draft Plans
      - Presentations of Final Plans to Clients:
          sections:
            - Presentations of Final Plans to Clients
      - Course Conclusion/Reflections:
          sections:
            - Final Reports/Plans