course:
  textbook: Water and Sanitation Infrastructure Planning in Developing Countries: A Comprehensive Guide
  chapters:
    - Introduction to the Class:
      sections:
        - State of the World’s Water and Sanitation Infrastructure
        - Problem Identification
        - Importance of Water and Sanitation Infrastructure Planning in Developing Countries
        subsections:
          - The Impact of Inadequate Water and Sanitation Infrastructure on Health and Development
          - Challenges Faced in Developing Countries
    - An Introduction to Water Supply and Sanitation Technologies:
      sections:
        - How to Define and Measure Access to Water Supply and Sanitation
        - Goals of W&S Investment: Human Health and Productivity Gains, the Environment
        - The Millennium Development Goals for Water and Sanitation
        - Emerging Technologies in Water Supply and Sanitation
      subsections:
        - Traditional Water Supply and Sanitation Technologies
        - Innovations and Advancements in Water Treatment and Distribution
    - Stakeholder Analysis:
      sections:
        - Actors in Water and Sanitation Infrastructure Planning and their Objectives
        - Institutional Options for W&S Planning and Policy in Developing Countries: Decentralization, Community Management, Privatization, etc.
        - Engaging Stakeholders in Planning and Decision Making Processes
      subsections:
        - Government Agencies and Ministries Involved in Water and Sanitation Planning
        - Non-Governmental Organizations and their Roles in Infrastructure Development
        - Community Engagement and Empowerment
    - The Evolution of W&S Infrastructure Planning in Developing Countries:
      sections:
        - Supply versus Demand-oriented Approaches
        - Historical Development of Water and Sanitation Infrastructure in Developing Countries
        - Lessons Learned from Past Projects and Initiatives
      subsections:
        - Top-down versus Bottom-up Planning Approaches
        - Case Studies of Successful Infrastructure Planning Projects
    - Urban Sanitation Projects with Community Participation:
      sections:
        - Experiences from Brazil
        - Community-Led Total Sanitation (CLTS) Programs
        - Challenges and Lessons Learned in Implementing Community Participation in Urban Sanitation Projects
      subsections:
        - Role of Community in Sanitation Planning and Implementation
        - Strategies for Mobilizing Community Participation
        - Monitoring and Evaluation of Community-Led Sanitation Projects
    - Providing Water and Sanitation Services to the Poor:
      sections:
        - Strategies and Obstacles
        - Innovative Financing Models for Pro-Poor Water and Sanitation Services
        - Addressing Social Inequalities in Access to Water and Sanitation
      subsections:
        - Targeting the Poor: Identifying and Reaching the Most Vulnerable Communities
        - Microfinance and Community-Based Financing Mechanisms
        - Social and Gender Equity in Water and Sanitation Provision
    - Community Participation in Water Supply and Sanitation:
      sections:
        - Alternative Models and Outcomes
        - Participatory Approaches in Water Supply and Sanitation Projects
        - Benefits and Challenges of Community-Led Initiatives
      subsections:
        - Community-Managed Water Systems and their Sustainability
        - Participatory Planning and Decision Making in Water Supply and Sanitation
        - Case Studies of Successful Community Participation Models
    - Financing and Pricing of Water and Sanitation Services:
      sections:
        - Revisiting the Privatization Debate
        - Public-Private Partnerships in Water and Sanitation Infrastructure
        - Tariff Setting and Cost Recovery Mechanisms
      subsections:
        - Privatization of Water and Sanitation Services: Pros and Cons
        - Models of Public-Private Cooperation in Infrastructure Development
        - Ensuring Affordability and Sustainability of Water and Sanitation Services
    - W&S Planning and the Environment:
      sections:
        - Environmental considerations in planning
        - Climate Change and its Impacts on Water and Sanitation Infrastructure
        - Integrated Water Resources Management in Developing Countries
      subsections:
        - Environmental Assessment and Mitigation Strategies in Infrastructure Planning
        - Adaptation and Resilience in the Face of Climate Change
        - Balancing Water Supply and Demand in a Changing Climate