textbook:
  Use of Joint Fact Finding in Science Intensive Policy Disputes, Part II:
    chapters:
    - Introduction and Overview:
        sections:
        - Goals and Scope of the Class
        - Traditional Adversarial Approach to Environmental Policy
        - Collaborative Problem Solving Approach
        - Scientist and Policy Maker Perspectives
    - Review of Fall Semester Student Papers:
        sections:
        - Concepts and Topics Covered in Fall
        - Unanswered Questions from Fall Seminar
        - Joint Fact Finding Model Development
    - Status of the Cape Wind Application Process:
        sections:
        - Progress Update
    - Offshore Wind Energy Sites:
        sections:
        - Potential Future Sites
        - Collaborative Process Approach to Permitting and Leasing
        - Citizen-Based Problem Solving Approach
    - Proposal Development for Cape Wind Issue:
        sections:
        - Joint Fact Finding Approach
        - Building on Fall Semester Efforts
    - Role-Play Simulations:
        sections:
        - Learning and Research Tools
        - Examples of Actual Simulations
    - Preparing for Role-Play Simulation:
        sections:
        - Playing Two Simulations
        - Designing Role-Play on Cape Wind Issue
    - Simulation Development:
        sections:
        - Rehearsal and Revision
        - Teaching Notes Preparation
    - Coastal Wind Development Workshop:
        sections:
        - Possible Participation
    - Rehearsing the Cape Wind Simulation:
        sections:
        - Inviting Outside Participants
    - Web Page Development:
        sections:
        - Accessing Simulation and Fall Semester Papers Online
        - Preparing for Publication in Working Paper Series