textbook:
  Use of Joint Fact Finding in Science Intensive Policy Disputes:
    chapters:
    - Introduction and Overview:
        sections:
        - The Challenge of using Scientific and Technical Information in Environmental Policy-Making
    - Discussion of Readings:
        sections:
        - Managing Scientific and Technical Information in Environmental Cases: Principles and Practices for Mediators and Facilitators
        - Should Scientists Remain Objective in Policy Decision-Making?
    - Guest Participant: P. Patrick Leahy, Assoc. Director for Geology, USGS:
        sections:
        - Discussion of Readings
    - Guest Participant: Stanley Ponce, Senior Advisor for Partnerships and Business Policy, USGS:
        sections:
        - Discussion of Readings
    - Framing a Joint Fact Finding Mission Statement in a Contested Ecosystem Management Situation:
        sections:
        - Cape Wind Controversy and Wind Energy in General
        - Current Status of Wind Power in General and Off Shore Wind Power in Particular
        - NIMBY (Not In My Backyard) Phenomenon: Challenges and Solutions
    - Invited Guest Participant to Present the Overview of the wind Controversy:
        sections:
        - Invited Guest Participant to Present Pro-View of the Controversy
    - Invited Guest Participant to Present Pro-View of the Controversy:
        sections:
        - Invited Guest Participant to Present the Con-View of the Controversy
    - Natural Resource Management in Rural Eastern Oregon:
        sections:
        - Guest Participant: Michael Mery, Chair Tomales Bay Watershed Council
    - Class Presentation:
        sections:
        - Class Presentation