textbook:
  Environmental Policy and Economics: A Comprehensive Guide
  chapters:
  - Introduction to Environmental Economics:
      sections:
      - Environmental economics and the role of government
  - Efficiency and Market:
      sections:
      - Efficiency and markets
  - Cost-Benefit Analysis and Public Goods:
      sections:
      - Cost-benefit analysis and public goods
  - Regulation and Taxes:
      sections:
      - Regulation and Pigouvian taxes
      - Coase and cap-and-trade
      - Pigouvian taxes
      - Topics in cap-and-trade
  - Risk and Uncertainty:
      sections:
      - Risk, uncertainty, and liability
  - International Competition:
      sections:
      - International competition
  - Environmental Kuznets Curves:
      sections:
      - Environmental Kuznets curves
  - The Porter Hypothesis:
      sections:
      - The Porter hypothesis
  - Regulation in Developing Economies:
      sections:
      - Regulation in developing economies
  - Valuation and Hedonics:
      sections:
      - Valuation and hedonics
  - Household Production and Discrete Choice:
      sections:
      - Household production and discrete choice
  - Natural Resource Economics:
      sections:
      - Natural resource economics
      - Natural resource economics II
  - Climate Change Policy:
      sections:
      - Climate change policy
  - South Pole Carbon Asset Management:
      sections:
      - South pole carbon asset management
  - Visit to MIT Cogeneration Plant:
      sections:
      - Visit to MIT cogeneration plant
  - OPOWER:
      sections:
      - OPOWER