textbook:
  Introduction to Sculpture: A Comprehensive Guide
    chapters:
    - Introduction:
        sections:
        - Course Number
        - Course Name
        - Resource Level
    - Readings:
        sections:
        - 'Page: readings'
        - Text
        - Information
        subsubsections:
        - Overview of Sculpture Materials
        - Sculpture Techniques
    - Lecture Notes:
        sections:
        - 'Page: lecture-notes'
        - Text
        - Information
        subsubsections:
        - Introduction to Sculpture History
        - Basic Principles of Sculpture Design
    - Recitations:
        sections:
        - 'Page: recitations'
        - Text
        - Information
        subsubsections:
        - Sculpture Safety Guidelines
        - Tools and Equipment for Sculpting
    - Assignments:
        sections:
        - 'Page: assignments'
        - Text
        - Information
        subsubsections:
        - Sculpting with Clay
        - Carving Techniques
    - Exams:
        sections:
        - 'Page: exams'
        - Text
        - Information
        subsubsections:
        - Sculpture Analysis
        - Sculpture Critique and Evaluation
    - Syllabus:
        sections:
        - 'Page: syllabus'
        - Information
    - Calendar:
        sections:
        - 'Page: calendar'
        - Text
        - Information
        subsubsections:
        - Important Dates and Deadlines
        - Class Schedule and Topics
    - Projects:
        sections:
        - 'Page: projects'
        - Text
        - Information
        subsubsections:
        - Sculpture Installation
        - Sculpture in Public Spaces