textbook:
  Gaoming Studio - "China":
    chapters:
    - title: Pre-semester Site Visit and Existing Context Analysis
      sections:
      - title: 10 Day Site Visit to Gaoming, China
        subsections:
        - title: Introduction to Gaoming
        - title: Cultural and Historical Significance
        - title: Study of Existing Infrastructure
        - title: Analysis of Environmental Factors
        - title: Observations and Initial Impressions
      - title: Present Initial Impressions and Ideas
        subsections:
        - title: Presentation of Initial Impressions
        - title: Brainstorming Session
        - title: Identifying Key Issues and Challenges
        - title: Generating Initial Ideas and Concepts
      - title: Gather Feedback
        subsections:
        - title: Feedback from Peers and Instructors
        - title: Expert Consultation and Review
        - title: Incorporating Feedback into the Analysis
      - title: Develop an understanding of the existing context
        subsections:
        - title: Socio-economic Analysis
        - title: Demographic Study
        - title: Urban Planning and Development
        - title: Infrastructure Assessment
        - title: Natural Environment Assessment
      - title: Research existing conditions
        subsections:
        - title: Gathering Data and Information
        - title: Analyzing Existing Policies and Regulations
        - title: Case Studies of Similar Projects
        - title: Reviewing Best Practices in Urban Design and Planning
    
    - title: Best Practices Research
      sections:
      - title: Draft recommendations
        subsections:
        - title: Identification of Key Challenges
        - title: Review of Best Practices in Urban Design
        - title: Developing Recommendations and Strategies
    
    - title: Site Visit
      sections:
      - title: 5 Day Site Visit to Gaoming
        subsections:
        - title: Study of Site Specifics and Constraints
        - title: Interaction with Local Stakeholders
        - title: Assessment of Site Potential
      - title: Present ideas
        subsections:
        - title: Presentation of Design Concepts
        - title: Explanation of Design Rationale
        - title: Addressing Feedback and Concerns
      - title: Gather feedback
        subsections:
        - title: Feedback from Local Community
        - title: Feedback from Experts and Professionals
        - title: Incorporating Feedback into Design Concepts
      - title: Perform further site research
        subsections:
        - title: Detailed Analysis of Site Conditions
        - title: Environmental Impact Assessment
        - title: Technical Feasibility Study
        - title: Preliminary Cost Estimation
    
    - title: Scenario Revisions
      sections:
      - title: Revise Draft Scenarios
        subsections:
        - title: Analysis of Initial Scenarios
        - title: Identifying Areas for Improvement
        - title: Development of Revised Scenarios
      - title: Presentation
        subsections:
        - title: Presentation of Revised Scenarios
        - title: Explanation of Changes Made
        - title: Addressing Questions and Concerns
    
    - title: Final Report
      sections:
      - title: Small group collaboration
        subsections:
        - title: Formation of Collaborative Teams
        - title: Distribution of Tasks and Responsibilities
        - title: Coordination and Communication
        - title: Conflict Resolution within Teams
      - title: Development of recommendations
        subsections:
        - title: Assessment of Design Options
        - title: Selection of Preferred Design
        - title: Detailed Design Development
        - title: Integration of Stakeholder Feedback
        - title: Preparation of Final Recommendations
      - title: Integration of water/hydrological factors into a modern city
        subsections:
        - title: Study of Water Management Strategies
        - title: Incorporating Sustainable Water Systems
        - title: Designing Waterfront Development
      - title: Watershed and natural ecosystem protection
        subsections:
        - title: Analysis of Watershed Characteristics
        - title: Identification of Ecological Hotspots
        - title: Designing Ecosystem Conservation Measures
      - title: Recreational activities
        subsections:
        - title: Assessment of Recreational Needs
        - title: Designing Parks and Public Spaces
        - title: Planning for Sports and Leisure Facilities
      - title: Housing
        subsections:
        - title: Housing Demand Analysis
        - title: Designing Affordable Housing Solutions
        - title: Planning for Mixed-Use Developments
      - title: Transportation
        subsections:
        - title: Evaluation of Existing Transportation Systems
        - title: Designing Efficient and Sustainable Transportation Networks
        - title: Integrating Public Transport and Non-Motorized Modes
      - title: Tourism
        subsections:
        - title: Analysis of Tourism Potential
        - title: Designing Tourist Attractions and Landmarks
        - title: Planning for Cultural and Heritage Tourism
    
    - title: Project Exhibition
      sections:
      - title: Display of final report
        subsections:
        - title: Designing an Engaging Exhibition Space
        - title: Preparation of Visual Displays
        - title: Interaction with Exhibition Visitors
      - title: Presentation of findings
        subsections:
        - title: Oral Presentation of Project Findings
        - title: Visual Presentation Aids and Tools
        - title: Addressing Questions and Feedback
      - title: Client interaction
        subsections:
        - title: Building Rapport with Clients
        - title: Understanding Client Expectations
        - title: Effective Communication with Clients
        - title: Incorporating Client Feedback in Final Report
      - title: Copyright concerns
        subsections:
        - title: Understanding Intellectual Property Rights
        - title: Copyright Protection for Design Works
        - title: Fair Use and Attribution Guidelines
        - title: Addressing Copyright Infringement Concerns
      - title: Image removal
        subsections:
        - title: Assessment of Image Usage Rights
        - title: Obtaining Proper Image Licenses
        - title: Image Removal Procedures
        - title: Replacing Removed Images with Licensed Alternatives
      - title: Student content retention
        subsections:
        - title: Ownership of Student Works
        - title: Retention and Archiving of Student Works
        - title: Student Consent and Permissions
        - title: Data Protection and Privacy Considerations
      - title: Permission usage
        subsections:
        - title: Obtaining Permissions for External Content
        - title: Proper Attribution and Acknowledgment
        - title: Compliance with Usage Guidelines
        - title: Documenting Permissions for Future Reference
      - title: Acknowledgment of student contributors
        subsections:
        - title: Recognition of Student Contributions
        - title: Acknowledgment in Final Report and Exhibition
        - title: Awards and Prizes for Outstanding Contributions
      - title: Student names
        subsections:
        - title: Handling and Protection of Student Personal Information
        - title: Privacy Laws and Regulations
        - title: Anonymity and Pseudonyms