textbook:
  'The Power of Place: Media Technology, Youth, and City Design and Development':
    chapters:
    - 'Chapter 1: Prologue: Gateway to an Unfolding Project':
        sections:
        - 'Section 1: Introduction to the West Philadelphia Landscape Project'
    - 'Chapter 2: Frameworks for Action: Water, Infrastructure, Architecture, People':
        sections:
        - 'Section 1: Understanding the Neighborhood'
        - 'Section 2: Tracing the Past, Envisioning the Future: Historical Context for Projects'
        - 'Section 3: The Internet and Community Design and Development'
    - 'Chapter 3: Proposals for Projects Due: Presentation and Discussion':
        sections:
        - 'Section 1: Revised Proposals Due'
        - 'Section 2: Determine Class Topics'
    - 'Chapter 4: Field Trip to Philadelphia':
        sections:
        - 'Section 1: Work with Sulzberger students'
    - 'Chapter 5: Work on Projects':
        sections:
        - 'Section 1: Finishing Projects'
        - 'Section 2: Reflecting on Projects'
        - 'Section 3: Discussion'
    - 'Chapter 6: Various Projects':
        sections:
        - 'Section 1: Searching Out the Lines - Christine Gaspar (PDF)'
        - 'Section 2: Revealing and Creating - Tracy Taylor'