course:
  Wave Motion in the Ocean and the Atmosphere: A Comprehensive Study
textbook:
  topics:
    - Waves:
        chapters:
          - Wave Properties
          - Wave Types
          - Wave Interactions
          - Wave Dispersion
          - Wave Reflection
          - Wave Refraction
          - Wave Diffraction
          - Wave Absorption
    - 'Slowly Varying Media: Ray Theory':
        chapters:
          - Ray Tracing
          - Snell's Law
          - Geometrical Optics
          - Wavefronts
          - Huygens' Principle
          - Fermat's Principle
          - Wave Propagation in Inhomogeneous Media
    - Surface Gravity Waves:
        chapters:
          - Gravity Waves on Water Surface
          - Wave Generation Mechanisms
          - Wave Dispersion Relation
          - Wave Breaking
          - Wave Energy Transfer
          - Wave Height and Period
          - Wave Spectra
    - Energy Equation:
        chapters:
          - Wave Energy Conservation
          - Energy Flux
          - Energy Dissipation Mechanisms
          - Wave-Induced Currents
          - Wave-Induced Turbulence
          - Wave-Induced Mixing
          - Wave-Induced Sediment Transport
    - Initial Value Problem - Homogeneous Medium:
        chapters:
          - Wave Equation
          - Initial Conditions
          - Boundary Conditions
          - Dispersion Relation
          - Group Velocity
          - Energy Conservation
          - Waveform Evolution
    - Internal Waves:
        chapters:
          - Internal Gravity Waves
          - Internal Wave Propagation
          - Internal Wave Reflection
          - Internal Wave Interference
          - Internal Wave Energy Flux
          - Internal Wave Breaking
          - Internal Wave Mixing
    - WKB Theory for Internal Gravity Waves - Non-Rotating Case:
        chapters:
          - WKB Approximation
          - WKBJ Method
          - WKB Dispersion Relation
          - WKB Phase Integral
          - WKB Wave Function
          - WKB Tunneling
          - WKB Reflection and Transmission
    - Internal Waves Modified by Rotation - Unbounded Fluid:
        chapters:
          - Coriolis Effect
          - Rossby Waves
          - Poincaré Waves
          - Kelvin Waves
          - Equatorial Waves
          - Planetary Waves
          - Edge Waves
    - 'The Oceanic Wave Guide: Normal Modes of a Stratified, Rotating Fluid':
        chapters:
          - Oceanic Stratification
          - Normal Modes
          - Resonant Frequencies
          - Rossby Radius of Deformation
          - Inertial Oscillations
          - Internal Tides
          - Internal Waves in the Oceanic Wave Guide
    - Unbounded Domain - Non-Rotating Reflection from a Solid Boundary:
        chapters:
          - Reflection Coefficient
          - Transmission Coefficient
          - Standing Waves
          - Waveguide Modes
          - Acoustic Waves
          - Seabed Interaction
          - Boundary Scattering
    - Laplace Tidal Equations on the Sphere:
        chapters:
          - Tidal Forces
          - Tidal Potential
          - Laplace's Tidal Equations
          - Tidal Harmonics
          - Tidal Constituents
          - Tidal Analysis
          - Tidal Prediction
    - Shallow Water Equations with Rotation - Poincaré Waves:
        chapters:
          - Shallow Water Approximation
          - Coriolis Effect in Shallow Water
          - Poincaré Waves in a Rotating System
          - Rossby Waves in a Shallow Water System
          - Equatorial Wave Dynamics
          - Wave Dispersion in Shallow Water
          - Wave Reflection and Transmission in Shallow Water
    - The Kelvin Wave:
        chapters:
          - Kelvin Helmholz Instability
          - Kelvin Wave Propagation
          - Kelvin Wave Characteristics
          - Kelvin Wave Dispersion Relation
          - Kelvin Wave Energy Flux
          - Kelvin Wave Reflection and Transmission
    - Rossby or Planetary Waves:
        chapters:
          - Rossby Wave Dispersion Relation
          - Rossby Wave Propagation
          - Rossby Wave Interactions
          - Rossby Wave Reflection
          - Rossby Wave Energy Transfer
          - Rossby Wave Breaking
          - Rossby Wave Mixing
    - Reflection and Energetics of Rossby Waves:
        chapters:
          - Reflection of Rossby Waves
          - Energetics of Rossby Waves
          - Rossby Wave Reflection Coefficient
          - Rossby Wave Transmission Coefficient
          - Rossby Wave Reflection and Transmission from Boundaries
          - Rossby Wave Dissipation Mechanisms
          - Rossby Wave Energy Flux
    - The Equatorial Wave Guide:
        chapters:
          - Equatorial Wave Types
          - Equatorial Wave Dispersion Relation
          - Equatorial Wave Propagation
          - Equatorial Wave Reflection
          - Equatorial Wave Energy Transfer
          - Equatorial Wave Breaking
          - Equatorial Wave Mixing
    - The Shelf Problem and Edge Waves:
        chapters:
          - Ocean Shelf Dynamics
          - Shelf Wave Propagation
          - Shelf Wave Characteristics
          - Shelf Wave Dispersion Relation
          - Shelf Wave Energy Flux
          - Edge Waves
          - Edge Wave Reflection and Transmission
    - Coastal Trapped Waves:
        chapters:
          - Coastal Trapped Wave Propagation
          - Coastal Trapped Wave Dispersion Relation
          - Coastal Trapped Wave Characteristics
          - Coastal Trapped Wave Energy Flux
          - Coastal Trapped Wave Reflection and Transmission
          - Coastal Trapped Wave Generation Mechanisms
          - Coastal Trapped Wave Interactions
    - Quasi-Geostrophic Potential Vorticity Equation in a Stratified Atmosphere:
        chapters:
          - Quasi-Geostrophic Approximation
          - Potential Vorticity Conservation
          - Potential Vorticity Equation
          - Potential Vorticity Dynamics
          - Stratified Atmosphere
          - Quasi-Geostrophic Instabilities
          - Quasi-Geostrophic Wave Propagation
    - Energetics with a Mean Flow for the Ocean and Atmosphere:
        chapters:
          - Mean Flow Effects on Wave Propagation
          - Wave-Mean Flow Interaction
          - Wave Energy Exchange with Mean Flow
          - Wave Dissipation by Mean Flow
          - Wave-Induced Mean Flow
          - Wave-Induced Mean Flow Instabilities
          - Mean Flow Modification by Waves
    - Topographically Forced, Steady Rossby Waves with a Zonal Flow in an Isothermal Atmosphere:
        chapters:
          - Topographic Rossby Waves
          - Steady Rossby Wave Propagation
          - Rossby Wave Characteristics in Isothermal Atmosphere
          - Rossby Wave Dispersion Relation near Zonal Flow
          - Rossby Wave Reflection and Transmission in Zonal Flow
          - Rossby Wave Energy Flux in Zonal Flow
          - Rossby Wave Dissipation Mechanisms near Topography
    - Waves with a Mean Flow - Ocean:
        chapters:
          - Mean Flow Effects on Ocean Waves
          - Wave-Mean Flow Interaction in the Ocean
          - Wave Energy Exchange with Mean Flow in the Ocean
          - Wave Dissipation by Mean Flow in the Ocean
          - Wave-Induced Mean Flow in the Ocean
          - Wave-Induced Mean Flow Instabilities in the Ocean
          - Mean Flow Modification by Waves in the Ocean