textbook:
  Wave Propagation and Applications:
    chapters:
    - Chapter 1: Sample Wave Problems
        sections:
        - Section 1.1: Introduction to Wave Propagation
            subsections:
            - Subsection 1.1.1: Basic Wave Properties
            - Subsection 1.1.2: Wave Equations
        - Section 1.2: Types of Wave Problems
            subsections:
            - Subsection 1.2.1: Transverse Waves
            - Subsection 1.2.2: Longitudinal Waves
        - Section 1.3: Wave Phenomena
            subsections:
            - Subsection 1.3.1: Reflection
            - Subsection 1.3.2: Refraction
            - Subsection 1.3.3: Diffraction
            - Subsection 1.3.4: Interference
        - Section 1.4: Wave Propagation in Different Mediums
            subsections:
            - Subsection 1.4.1: Waves in Solids
            - Subsection 1.4.2: Waves in Liquids
            - Subsection 1.4.3: Waves in Gases
        - Section 1.5: Wave Problems in Real-World Scenarios
            subsections:
            - Subsection 1.5.1: Seismic Waves
            - Subsection 1.5.2: Acoustic Waves
            - Subsection 1.5.3: Electromagnetic Waves
    - Chapter 2: One Dimensional Waves
        sections:
        - Section 2.1: Introduction to One Dimensional Waves
            subsections:
            - Subsection 2.1.1: Wave Characteristics
            - Subsection 2.1.2: Wave Equations
        - Section 2.2: Wave Propagation in Strings
            subsections:
            - Subsection 2.2.1: Standing Waves
            - Subsection 2.2.2: Harmonics
        - Section 2.3: Wave Propagation in Rods
            subsections:
            - Subsection 2.3.1: Longitudinal Waves
            - Subsection 2.3.2: Dispersion
        - Section 2.4: Wave Propagation in Bars
            subsections:
            - Subsection 2.4.1: Transverse Waves
            - Subsection 2.4.2: Mode Analysis
    - Chapter 3: Two Dimensional Waves
        sections:
        - Section 3.1: Introduction to Two Dimensional Waves
            subsections:
            - Subsection 3.1.1: Wavefronts
            - Subsection 3.1.2: Huygens' Principle
        - Section 3.2: Wave Propagation in Rectangular Areas
            subsections:
            - Subsection 3.2.1: Wave Interference
            - Subsection 3.2.2: Wave Diffraction
        - Section 3.3: Wave Propagation in Circular Areas
            subsections:
            - Subsection 3.3.1: Circular Wavefronts
            - Subsection 3.3.2: Wave Reflection and Refraction
        - Section 3.4: Wave Propagation in Irregular Areas
            subsections:
            - Subsection 3.4.1: Wave Scattering
            - Subsection 3.4.2: Wave Absorption
    - Chapter 4: Waves in Water
        sections:
        - Section 4.1: Introduction to Water Waves
            subsections:
            - Subsection 4.1.1: Ocean Wave Characteristics
            - Subsection 4.1.2: Water Wave Equations
        - Section 4.2: Wave Motion in Shallow Water
            subsections:
            - Subsection 4.2.1: Wave Dispersion
            - Subsection 4.2.2: Wave Shoaling
        - Section 4.3: Wave Motion in Deep Water
            subsections:
            - Subsection 4.3.1: Wave Reflection and Transmission
            - Subsection 4.3.2: Wave Breaking
            - Subsection 4.3.3: Tsunamis
        - Section 4.4: Wave Motion in Coastal Areas
            subsections:
            - Subsection 4.4.1: Wave Refraction
            - Subsection 4.4.2: Wave Erosion and Deposition
    - Chapter 5: Wave Localization
        sections:
        - Section 5.1: Introduction to Wave Localization
            subsections:
            - Subsection 5.1.1: Wave Interference and Superposition
            - Subsection 5.1.2: Standing Wave Patterns
        - Section 5.2: Localization in Disordered Systems
            subsections:
            - Subsection 5.2.1: Anderson Localization
            - Subsection 5.2.2: Multiple Scattering
        - Section 5.3: Localization in Periodic Structures
            subsections:
            - Subsection 5.3.1: Photonic Crystals
            - Subsection 5.3.2: Phononic Crystals
    - Chapter 6: Forced Dispersive Waves Along a Narrow Channel
        sections:
        - Section 6.1: Introduction to Forced Dispersive Waves
            subsections:
            - Subsection 6.1.1: Wave Dispersion
            - Subsection 6.1.2: Forced Wave Equations
        - Section 6.2: Wave Propagation in Narrow Channels
            subsections:
            - Subsection 6.2.1: Wave Reflection and Transmission
            - Subsection 6.2.2: Wave Dispersion and Attenuation
        - Section 6.3: Wave Interactions in Narrow Channels
            subsections:
            - Subsection 6.3.1: Wave Interference
            - Subsection 6.3.2: Wave Scattering
    - Chapter 7: Internal Waves in a Stratified Fluid
        sections:
        - Section 7.1: Introduction to Internal Waves
            subsections:
            - Subsection 7.1.1: Density Stratification
            - Subsection 7.1.2: Internal Wave Equations
        - Section 7.2: Internal Wave Propagation in the Ocean
            subsections:
            - Subsection 7.2.1: Internal Wave Generation
            - Subsection 7.2.2: Internal Wave Reflection and Refraction
        - Section 7.3: Internal Wave Interactions
            subsections:
            - Subsection 7.3.1: Wave-Wave Interactions
            - Subsection 7.3.2: Wave-Current Interactions
    - Chapter 8: Wave Propagation and Technology
        sections:
        - Section 8.1: Introduction to Wave Technology
            subsections:
            - Subsection 8.1.1: Wave-Based Communication Systems
            - Subsection 8.1.2: Wave-Based Sensing and Imaging
        - Section 8.2: Wave Propagation in Optical Fibers
            subsections:
            - Subsection 8.2.1: Fiber Optic Communication
            - Subsection 8.2.2: Fiber Optic Sensors
        - Section 8.3: Wave Propagation in Wireless Communication
            subsections:
            - Subsection 8.3.1: Electromagnetic Waves and Antennas
            - Subsection 8.3.2: Signal Propagation and Multipath Fading
        - Section 8.4: Wave Propagation in Radar Systems
            subsections:
            - Subsection 8.4.1: Radar Principles and Applications
            - Subsection 8.4.2: Target Detection and Tracking