textbook:
  'Computational Design I: Theory and Applications':
    chapters:
    - Introduction:
        sections:
        - Basic Concepts:
            subsections:
            - Introduction to Computational Design
            - Overview of Basic Concepts
            - Applications of Computational Design
        - Shape Representation:
            subsections:
            - Introduction to Shape Representation
            - Geometric and Topological Representations
            - Data Structures for Shape Representation
        - Shape Arithmetic:
            subsections:
            - Introduction to Shape Arithmetic
            - Operations on Shapes
            - Shape Manipulation Techniques
        - Shape Rules:
            subsections:
            - Introduction to Shape Rules
            - Rule-based Modeling
            - Shape Rule Systems
    - Rule Application and Parametric Design:
        sections:
        - Nondeterminism:
            subsections:
            - Introduction to Nondeterminism
            - Non-deterministic Rule Application
            - Non-deterministic Shape Generation
        - Emergence:
            subsections:
            - Introduction to Emergence
            - Emergent Behavior in Computational Design
            - Harnessing Emergence in Design
        - Labeling:
            subsections:
            - Introduction to Labeling
            - Labeling Techniques in Computational Design
            - Applications of Labeling in Design Problems
        - Parametric Design and Grammars:
            subsections:
            - Introduction to Parametric Design
            - Grammar-based Design Systems
            - Parametric Design Approaches and Methods
    - Style and Analysis:
        sections:
        - The Immediacy of the Artist's Mark in Computation:
            subsections:
            - Introduction to the Immediacy of the Artist's Mark in Computation
            - Expressing Artistic Intent in Computational Design
            - Evaluating the Artist's Mark in Computation
        - Artificial Evolution for Computer Graphics:
            subsections:
            - Introduction to Artificial Evolution for Computer Graphics
            - Evolutionary Algorithms in Computational Design
            - Evolutionary Approaches for Generating Graphics
    - Inference and Problem Decomposition:
        sections:
        - Inference Problem Decomposition and Meaning:
            subsections:
            - Introduction to Inference Problem Decomposition and Meaning
            - Inference Techniques in Computational Design
            - Problem Decomposition Approaches in Design
    - Creative Design:
        sections:
        - Introduction:
            subsections:
            - Introduction to Creative Design
            - The Role of Creativity in Computational Design
            - Creative Design Strategies and Techniques
        - Emergence and Predictability:
            subsections:
            - Introduction to Emergence and Predictability
            - Predictability in Computational Design
            - Emergence and Unpredictability in Design
        - Final Project Review:
            subsections:
            - Introduction to Final Project Review
            - Guidelines for Final Project Review
            - Examples of Successful Final Projects
    - Assignments:
        sections:
        - Assignment 1 due:
            subsections:
            - Requirements for Assignment 1
            - Submission Guidelines for Assignment 1
        - Assignment 2 due:
            subsections:
            - Requirements for Assignment 2
            - Submission Guidelines for Assignment 2
        - Assignment 3 due:
            subsections:
            - Requirements for Assignment 3
            - Submission Guidelines for Assignment 3
        - Assignment 4 due:
            subsections:
            - Requirements for Assignment 4
            - Submission Guidelines for Assignment 4
        - Additional Assignments:
            subsections:
            - Requirements for Additional Assignments
            - Submission Guidelines for Additional Assignments
    - Calendar:
        sections:
        - Key Dates:
            subsections:
            - Important Dates for the Course
            - Deadlines for Assignments and Projects
    - Projects:
        sections:
        - Final Project Review:
            subsections:
            - Introduction to Final Project Review
            - Guidelines for Final Project Review
            - Examples of Successful Final Projects
        - Individual Projects:
            subsections:
            - Requirements for Individual Projects
            - Project Proposal Guidelines
            - Project Development and Evaluation