```yaml
course:
  textbook: Surface Processes and Landscape Evolution: Understanding Earth's Dynamic Surface
    chapters:
    - Introduction to Surface Processes and Landscape Evolution:
        sections:
        - Geomorphic Systems
        - The Earth's Surface: An Overview
        - The Role of Surface Processes in Landscape Evolution
    - Fluid Mechanics and Surface Flows:
        sections:
        - Flow Mechanics
        - Types of Flow: Laminar and Turbulent Flow
        - Flow Velocity and Reynolds Number
    - River Dynamics and Channel Morphology:
        sections:
        - Alluvial Channels
        - Channel Formation and Evolution
        - Channel Patterns and River Networks
    - Flow and Sediment Transport:
        sections:
        - Flow Around Bends
        - Sediment Transport Mechanisms
        - Bedload and Suspended Load Transport
        - Sediment Sorting and Deposition
    - River Profiles and Longitudinal Profiles:
        sections:
        - Alluvial Profiles
        - River Profile Development and Shape
        - Stream Gradient and Base Level
    - Erosion and Erosional Landscapes:
        sections:
        - Erosional Channel Networks
        - Rills, Gullies, and Small Channels
        - Incised Valleys and Canyons
        - River Terraces and Floodplains
    - Bedrock Channels and Mountain Landscapes:
        sections:
        - Bedrock Channels
        - River Incision and Knickpoints
        - The Formation of Gorges and Waterfalls
        - The Role of Tectonics in Mountain Building
    - Hillslope Processes and Landforms:
        sections:
        - Hillslope Evolution
        - Weathering and Mass Movement
        - Slope Stability and Landslides
        - Soil Creep and Solifluction
    - Mass Wasting and Slope Failure:
        sections:
        - Mass Wasting
        - Types of Mass Wasting
        - Causes and Triggers of Mass Wasting
        - Landslide Hazards and Mitigation Measures
    - Climate and Tectonics in Landscape Evolution:
        sections:
        - Climate-Tectonic Interactions
        - Climate Change and Landscape Response
        - Tectonic Activity and Landscape Modification
        - Landscape Evolution in Different Tectonic Settings
    - Human Interaction with Surface Processes:
        sections:
        - Human Impact on Surface Processes
        - Land-Use Change and Surface Hydrology
        - Surface Processes and Environmental Management
        - Surface Processes and Engineering Geology
```