```yaml
textbook:
  Environmental Engineering Applications of Geographic Information Systems:
    chapters:
      - Introduction to GIS:
          sections:
            - Basic ArcGIS Tutorial
            - Data Types
            - Map Making in GIS
      - Map Layout and Cartography:
          sections:
            - Map Projections
            - Using Map Projections
            - Raster Data
            - Raster Processing
      - Digital Elevation Models:
          sections:
            - DEMs
            - Raster Processing
            - Hydrologic Functions
      - Vector Processing:
          sections:
            - Vector Processing
            - Site Selection Exercise (Vector Analysis)
      - Cost-Distance Modeling:
          sections:
            - Assembling a Cost-Distance Model
            - Raster Processing
            - Cost Path Modeling
      - Mobile GIS:
          sections:
            - Planning for Field Work
      - Spatial Data:
          sections:
            - Querying Data on a Map
      - Project Work:
          sections:
            - Project Introductions
            - Project Work Time
            - Project Presentations
      - Final Exam:
          sections:
            - Final Exam
      - GIS Data Analysis:
          sections:
            - Data Collection Methods
            - Spatial Data Quality
            - Data Integration Techniques
      - Geodatabases:
          sections:
            - Introduction to Geodatabases
            - Database Design
            - Geodatabase Management
      - Geoprocessing:
          sections:
            - Introduction to Geoprocessing
            - Geoprocessing Tools
            - Geoprocessing Workflows
      - Network Analysis:
          sections:
            - Introduction to Network Analysis
            - Network Data Model
            - Network Analysis Techniques
      - Spatial Interpolation:
          sections:
            - Introduction to Spatial Interpolation
            - Interpolation Methods
            - Validation of Interpolated Surfaces
      - Spatial Analysis in 3D:
          sections:
            - Introduction to 3D Analysis
            - 3D Data Models
            - 3D Analysis Techniques
      - Spatial Statistics:
          sections:
            - Introduction to Spatial Statistics
            - Spatial Autocorrelation
            - Point Pattern Analysis
            - Spatial Regression Analysis
      - Web GIS:
          sections:
            - Introduction to Web GIS
            - Web Mapping
            - Web GIS Applications
      - Remote Sensing and GIS Integration:
          sections:
            - Introduction to Remote Sensing
            - Remote Sensing Data Processing
            - Remote Sensing and GIS Integration Techniques
      - GIS for Environmental Impact Assessment:
          sections:
            - Introduction to Environmental Impact Assessment
            - Data Collection for Environmental Impact Assessment
            - Spatial Analysis for Environmental Impact Assessment
      - GIS for Natural Resource Management:
          sections:
            - Introduction to Natural Resource Management
            - Data Collection for Natural Resource Management
            - Spatial Analysis for Natural Resource Management
      - GIS for Urban Planning:
          sections:
            - Introduction to Urban Planning
            - Data Collection for Urban Planning
            - Spatial Analysis for Urban Planning
      - GIS for Disaster Management:
          sections:
            - Introduction to Disaster Management
            - Data Collection for Disaster Management
            - Spatial Analysis for Disaster Management
      - GIS for Climate Change Analysis:
          sections:
            - Introduction to Climate Change Analysis
            - Data Collection for Climate Change Analysis
            - Spatial Analysis for Climate Change Analysis
```