textbook:
  Springfield Studio: A Comprehensive Guide to Urban Neighborhood Decline and Revitalization
  chapters:
    - Chapter 1: Course Introduction
      sections:
        - Section 1.1: Urban Neighborhood Decline: Causes, Consequences, Challenges in Springfield
    - Chapter 2: Ways of Seeing: Assessing the Physical and Social Environment of a Community
      sections:
        - Section 2.1: Field Trip to the North End, Springfield, Massachusetts
        - Section 2.2: Field Trip Debriefing and Resource Review
        - Section 2.3: Work Session: Urban Design Analysis Goals and Techniques
    - Chapter 3: Community Needs: Programming
      sections:
        - Section 3.1: Community Capacity
        - Section 3.2: Physical Design Strategies Part 1
        - Section 3.3: Physical Design Strategies Part 2
    - Chapter 4: Working Session
      sections:
        - Section 4.1: Presentation of Student Work
        - Section 4.2: Working Session: Presentation Revisions
    - Chapter 5: Field Trip to North End, Springfield: Client Presentations
      sections:
        - Section 5.1: Working Session: Development of a Conceptual Plan
        - Section 5.2: Working Session: Development of a Conceptual Plan
        - Section 5.3: Presentations of Conceptual Plans
    - Chapter 6: Working Session
      sections:
        - Section 6.1: Working Session
        - Section 6.2: Working Session
        - Section 6.3: Working Session
    - Chapter 7: Working Session: Synthesis of Ideas
      sections:
        - Section 7.1: Working Session: Synthesis of Ideas
        - Section 7.2: Working Session: Synthesis of Ideas
    - Chapter 8: Synthesis - Final Plan Integration, Key Findings and Themes
      sections:
        - Section 8.1: Presentation of Draft Plans
        - Section 8.2: Presentation of Draft Plans
    - Chapter 9: Course Conclusion / Reflections
      sections:
        - Section 9.1: Final Report / Plans Due
        - Section 9.2: Presentations to the Client
        - Section 9.3: Final Presentations