```yaml
textbook:
  Dialogue in Art, Architecture, and Urbanism: Exploring the Intersection of Creativity and the Built Environment
  chapters:
    - Introduction and Overview:
        sections:
        - Slideshow of examples of Public Artworks
        - Analysis of Muntadas’ own work in relation to public art
        - Understanding the role of dialogue in art, architecture, and urbanism
    - Showcasing Student Work:
        sections:
        - Presentation of previous work by students
        - Analysis and critique of student work by instructors and peers
    - Collaborations between Artists and Architects:
        sections:
        - Case study: Acconci + Holl’s Storefront for Art and Architecture
        - Case study: Barbara Kruger’s Collaboration with Smith-Miller and Hawkinson
        - Case study: Exploring the work of Silvia Kolbowski and her collaborations
        - Analysis of the impact of artist-architect collaborations on the built environment
    - The Big Dig/Central Artery Project:
        sections:
        - Introduction to the Big Dig/Central Artery Project and its significance
        - Examination of the challenges faced during the project and their resolutions
        - Analysis of the impact of the Big Dig/Central Artery Project on urbanism
    - History of the Central Artery:
        sections:
        - Presentation by Hubert Murray, Architect/Planner for Boston’s Central Artery Project
        - Discussion of the historical context and development of the Central Artery
    - Critical Regionalism Revisited:
        sections:
        - Field Trip to Yale University to attend lecture by Kenneth Frampton and Arjun Appadurai
        - Analysis and critique of critical regionalism in the context of art, architecture, and urbanism
    - Visiting Artist: Kelly Dobson:
        sections:
        - In-depth exploration of the work and contributions of Kelly Dobson
        - Discussion and analysis of the role of visiting artists in the course
    - Students’ Proposals for Big Dig Interventions:
        sections:
        - Pin-up of Students’ Proposals for interventions in the Big Dig/Central Artery Project
        - Analysis and critique of student proposals by instructors and visiting critics
    - Planned Cities and Public Art/Architecture:
        sections:
        - Introduction to Brasilia and its significance as a planned city
        - Discussion of other planned cities and their deployments of Public Art and Architecture
        - Analysis of the relationship between planned cities and public art/architecture
    - Field Trip to Brasilia:
        sections:
        - Visit to Brasilia to experience its architecture and public art
        - Reflection and analysis of the impact of Brasilia on urbanism and the built environment
    - Discussion of Brasilia Trip:
        sections:
        - Presentation of photographs and film footage from the trip to Brasilia
        - Analysis and reflection on the experience and lessons learned during the trip
    - Films:
        sections:
        - Analysis and interpretation of Chris Marker's Sans Soleil
        - Analysis and interpretation of Berlin Babylon directed by Hubertus Siegert
    - Final Critique of Students’ Projects:
        sections:
        - Critique session with Visiting Critics Wendy Jacob, Hubert Murray, and Laurie Palmer
        - Analysis and feedback on students' final projects by instructors and visiting critics
    - Student Projects:
        sections:
        - In-depth exploration and analysis of interventions proposed by students for the Rose Kennedy Greenway
        - Reflection on the process and outcomes of student projects
```
```