textbook:
  Role of Science and Scientists in Collaborative Approaches to Environmental Policymaking: A Comprehensive Guide

chapters:
  - Introduction and Overview:
    sections:
      - Goals and Scope of the Class
      - Background of Guest Participants
      - Traditional Role of Science in Society
      - Changing Role of Science in Contemporary Society
      subsections: []
  
  - The Role of Science in Environmental Policy-Making:
    sections:
      - Collaborative Processes for Policy Decisions
      - Collaborative Learning and Citizen Involvement
    subsections: []
  
  - Collaborative Approaches to Adaptive Management and Governance:
    sections:
      - Adaptive Management
      - Adaptive Governance
      - Ecosystem Based Management
    subsections: []
  
  - The Role of the Citizen - Local and Indigenous Knowledge:
    sections:
      - Importance of Local and Indigenous Knowledge
    subsections: []
  
  - Preliminary Student Presentations:
    sections:
      - Presentation Topics
    subsections: []
  
  - Last Day of Class:
    sections:
      - Course Wrap-up
    subsections: []