textbook:
  'Environmental Management Practicum: Brownfield Redevelopment':
    chapters:
      - Chapter 1:
        sections:
          - Section 1:
            subsections:
              - Subsection 1
              - Subsection 2
              - Subsection 3
              - Subsection 4
              - Subsection 5
              - Subsection 6
              - Subsection 7
              - Subsection 8
              - Subsection 9
              - Subsection 10
      - Chapter 2:
        sections:
          - Section 1:
            subsections:
              - Subsection 1
              - Subsection 2
              - Subsection 3
              - Subsection 4
              - Subsection 5
              - Subsection 6
              - Subsection 7
              - Subsection 8
              - Subsection 9
              - Subsection 10
      - Chapter 3:
        sections:
          - Section 1:
            subsections:
              - Subsection 1
              - Subsection 2
              - Subsection 3
              - Subsection 4
              - Subsection 5
              - Subsection 6
              - Subsection 7
              - Subsection 8
              - Subsection 9
              - Subsection 10
      - Chapter 4:
        sections:
          - Section 1:
            subsections:
              - Subsection 1
              - Subsection 2
              - Subsection 3
              - Subsection 4
              - Subsection 5
              - Subsection 6
              - Subsection 7
              - Subsection 8
              - Subsection 9
              - Subsection 10
      - Chapter 5:
        sections:
          - Section 1:
            subsections:
              - Subsection 1
              - Subsection 2
              - Subsection 3
              - Subsection 4
              - Subsection 5
              - Subsection 6
              - Subsection 7
              - Subsection 8
              - Subsection 9
              - Subsection 10
    - Appendix:
        sections:
          - Section 1:
            subsections:
              - Subsection 1
              - Subsection 2
              - Subsection 3
              - Subsection 4
              - Subsection 5
              - Subsection 6
              - Subsection 7
              - Subsection 8
              - Subsection 9
              - Subsection 10