textbook:
  Technology, Law, and the Working Environment: A Comprehensive Guide

chapters:
  - Chapter 1: The Nature of the Harm and Options for Regulatory Intervention
    sections:
      - Section 1.1: Occupational Health and Safety
      - Section 1.2: Risk Assessment
      - Section 1.3: Regulation of Labor-Management Relations

  - Chapter 2: Administrative Law
    sections:
      - Section 2.1: Principles and Procedures
      - Section 2.2: Rulemaking and Adjudication
      - Section 2.3: Judicial Review

  - Chapter 3: Toxics Information Transfer in the Workplace
    sections:
      - Section 3.1: Hazard Communication
      - Section 3.2: Safety Data Sheets
      - Section 3.3: Workplace Labeling

  - Chapter 4: Economic Issues in Occupational Health and Safety
    sections:
      - Section 4.1: Cost-Benefit Analysis
      - Section 4.2: Economic Incentives for Compliance
      - Section 4.3: Workers' Compensation

  - Chapter 5: Retaliatory Employment Practices
    sections:
      - Section 5.1: Whistleblower Protection
      - Section 5.2: Retaliation Claims
      - Section 5.3: Remedies and Enforcement

  - Chapter 6: Biotechnology: Biogenetic Monitoring
    sections:
      - Section 6.1: Genetic Testing
      - Section 6.2: Privacy and Consent Issues
      - Section 6.3: Ethical and Legal Considerations

  - Chapter 7: Consumer and Workplace Products
    sections:
      - Section 7.1: Product Liability
      - Section 7.2: Product Safety Regulations
      - Section 7.3: Consumer Protection Laws

  - Chapter 8: Compensation for Exposure to Toxic Substances
    sections:
      - Section 8.1: Workers' Compensation Benefits
      - Section 8.2: Toxic Tort Litigation
      - Section 8.3: Compensation Funds

  - Chapter 9: Pollution Prevention/Toxics Use Reduction and Primary Accident Prevention
    sections:
      - Section 9.1: Pollution Prevention Strategies
      - Section 9.2: Toxics Use Reduction Programs
      - Section 9.3: Accident Prevention Measures

subsections:
  - Section 1.1.1: Occupational Health and Safety Regulations
  - Section 1.1.2: Workplace Safety Inspections
  - Section 1.2.1: Quantitative Risk Assessment
  - Section 1.2.2: Qualitative Risk Assessment
  - Section 1.3.1: Collective Bargaining Agreements
  - Section 1.3.2: Unfair Labor Practices

  - Section 3.1.1: Material Safety Data Sheets
  - Section 3.1.2: Chemical Hazard Classification
  - Section 3.2.1: Importance of Safety Data Sheets
  - Section 3.2.2: SDS Implementation
  - Section 3.3.1: Workplace Labeling Requirements
  - Section 3.3.2: Labeling Hazards and Precautions

  - Section 4.1.1: Cost Analysis Techniques
  - Section 4.1.2: Benefit Analysis Techniques
  - Section 4.2.1: Financial Incentives for Compliance
  - Section 4.2.2: Non-Financial Incentives for Compliance
  - Section 4.3.1: Types of Workers' Compensation Benefits
  - Section 4.3.2: Claims Process and Eligibility

  - Section 5.1.1: Protected Whistleblowing Activities
  - Section 5.1.2: Whistleblower Confidentiality
  - Section 5.2.1: Types of Retaliation Claims
  - Section 5.2.2: Burden of Proof in Retaliation Claims
  - Section 5.3.1: Legal Remedies for Retaliation
  - Section 5.3.2: Enforcement Agencies and Procedures

  - Section 6.1.1: Genetic Testing Technologies
  - Section 6.1.2: Genetic Test Results and Interpretation
  - Section 6.2.1: Privacy Laws and Regulations
  - Section 6.2.2: Consent Requirements for Genetic Testing
  - Section 6.3.1: Ethical Considerations in Biogenetic Monitoring
  - Section 6.3.2: Legal Framework for Biogenetic Monitoring

  - Section 7.1.1: Product Liability Claims and Defenses
  - Section 7.1.2: Strict Liability and Negligence in Product Liability
  - Section 7.2.1: Testing and Certification of Product Safety
  - Section 7.2.2: Regulatory Compliance for Product Safety
  - Section 7.3.1: Consumer Protection Laws and Agencies
  - Section 7.3.2: Remedies for Consumer Protection Violations

  - Section 8.1.1: Compensation for Medical Expenses
  - Section 8.1.2: Compensation for Lost Wages
  - Section 8.2.1: Toxic Tort Litigation Process
  - Section 8.2.2: Establishing Causation in Toxic Tort Cases
  - Section 8.3.1: Compensation Funds for Toxic Exposure Victims
  - Section 8.3.2: Eligibility and Claim Process for Compensation Funds

  - Section 9.1.1: Source Reduction Strategies
  - Section 9.1.2: Process Modification Strategies
  - Section 9.2.1: Implementing Toxics Use Reduction Programs
  - Section 9.2.2: Monitoring and Reporting Toxics Use
  - Section 9.3.1: Safety Inspections and Audits
  - Section 9.3.2: Accident Prevention Plans and Training