textbook:
  Design for Sustainability: A Comprehensive Guide to Sustainable Design in Engineering and Architecture
  chapters:
    - Introduction to Sustainability:
        sections:
        - The Importance of Sustainability in Design
        - Understanding the Green Engineer's Role
        - Sustainable Practices in the Building Industry
        - Examining Current U.S. Trends in Sustainability
    - Life Cycle Assessment:
        sections:
        - Introduction to Life Cycle Assessment (LCA)
        - Applying LCA for Sustainable Design
        - Case Study: The Genzyme Building and Its Sustainable Design Features
        - Evaluating the Environmental Impact of Design Choices
    - Energy and Materials:
        sections:
        - Energy Efficiency in Buildings
        - Renewable Energy Sources for Sustainable Design
        - Sustainable Materials Selection and Usage
        - Recycling and Upcycling in Design
    - Water and Sanitation:
        sections:
        - Water Conservation Strategies in Design
        - Sustainable Sanitation Systems
        - Rainwater Harvesting and Greywater Recycling
        - Managing Water Resources in Urban Environments
    - Sustainable Transportation:
        sections:
        - Integrating Sustainable Transportation into Design
        - Promoting Public Transit and Active Transportation
        - Designing for Bicycle and Pedestrian Accessibility
        - Electrification of Transportation and Infrastructure
    - Social Sustainability:
        sections:
        - Understanding Social Equity in Design
        - Designing Inclusive Spaces for All
        - Community Engagement and Participatory Design
        - Addressing Health and Well-being in Design
    - Circular Economy:
        sections:
        - Introduction to the Circular Economy
        - Designing for Product Life Extension
        - Closed-loop Systems and Waste Reduction
        - Sustainable Consumption and Production Patterns
    - Sustainable Urban Design:
        sections:
        - Principles of Sustainable Urban Design
        - Green Infrastructure and Urban Biodiversity
        - Designing Resilient and Climate-Adaptive Cities
        - Transforming Urban Spaces for Sustainability
    - Project Work and Presentations:
        sections:
        - Stata Center Tour: Exploring Sustainable Design Features
        - Project Working Session: Applying Sustainable Design Principles
        - Final Presentations: Showcasing Innovative Sustainable Designs