textbook:
  'Cellular Solids: Structure, Properties and Applications':
    chapters:
      - Introduction and Overview:
        sections:
          - Processing of cellular solids
          - Structure of cellular solids
      - Honeycombs:
        sections:
          - In-plane behaviour
          - Out-of-plane behaviour
      - Natural Honeycombs:
        sections:
          - Wood
          - Cork
      - Foams:
        sections:
          - Linear elasticity
          - Strength
          - Densification
          - Fracture
          - Microstructural design
          - Lattice materials
          - Property charts
          - Thermal properties
      - Exam Review:
        sections: []
      - Trabecular Bone:
        sections: []
      - Osteoporosis and Evolution:
        sections: []
      - Tissue Engineering Scaffolds:
        sections:
          - Case study: Osteochondral scaffold
      - Cell-Scaffold Interactions:
        sections:
          - Attachment
          - Morphology
          - Contraction
          - Migration
          - Differentiation
      - Applications:
        sections:
          - Energy absorption in foams
          - Sandwich panels
      - Natural Sandwich Structures + Density Gradients:
        sections: []
      - Biomimicking:
        sections: []
      - How I Became a Professor:
        sections: []