textbook:
  'Revitalizing Urban Main Streets: St. Claude Avenue, New Orleans':
    chapters:
      - Chapter 1: Course Introduction
        sections:
          - Section 1.1: Main Street Sites and Issues
          - Section 1.2: Urban Neighborhood Decline: Causes, Consequences, Challenges
      - Chapter 2: New Orleans Background
        sections:
          - Section 2.1: Social, Political and Development History
          - Section 2.2: Katrina Impact, Disaster Recovery and New Orleans’ Planning Process
          - Section 2.3: Urban Design and Development: Ways of Seeing and Listening
      - Chapter 3: Project Discussion and Planning
        sections:
          - Section 3.1: Expectations, goals, and apprehensions
          - Section 3.2: First experiences and thoughts
          - Section 3.3: Defining shared issues or questions to examine through reflection
          - Section 3.4: How our personal values shape our work
          - Section 3.5: Looking backward and forward
          - Section 3.6: Commercial revitalization practice
          - Section 3.7: Critical moments: personal understanding
      - Chapter 4: Field Trip and Interviews
        sections:
          - Section 4.1: Field trip walking tour of St. Claude Avenue commercial corridor
          - Section 4.2: Interview transcriptions
      - Chapter 5: Analysis and Documentation
        sections:
          - Section 5.1: Summary of background reports and key documents
          - Section 5.2: Draft of phase I existing conditions analysis section of plan
      - Chapter 6: Final Report
        sections:
          - Section 6.1: The following is the final report prepared by the students in the Spring 2009 Revitalizing Urban Main Streets course. Used with permission.
          - Section 6.2: 'St Claude in Common.'
    subsubtopics:
      - Subsection 1.2.1: Understanding Main Street Sites
      - Subsection 1.2.2: Analyzing Main Street Issues
      - Subsection 2.3.1: Visual Perception in Urban Design
      - Subsection 2.3.2: Listening to Community Voices
      - Subsection 3.7.1: Reflecting on Personal Experiences
      - Subsection 4.2.1: Extracting Insights from Interviews
      - Subsection 5.2.1: Evaluating Existing Conditions
      - Subsection 6.1.1: Final Report Overview
      - Subsection 6.1.2: Methodology and Findings
      - Subsection 6.2.1: Case Studies in Successful Revitalization
      - Subsection 6.2.2: Implementing 'St Claude in Common'