textbook:
  Urban Design Policy and Action: A Comprehensive Guide

chapters:
  - Introduction to Urban Design Policy:
    sections:
      - Why should government get involved in urban design?
      - Understanding the role of government in shaping urban design
      - The impact of urban design on communities
      - Benefits and challenges of government intervention in urban design
      - The role of urban design policy in promoting sustainable development

  - Tools for Implementing Urban Design Policy:
    sections:
      - The five (plus or minus) tools for implementing urban design policy
      - Ownership and operation: Public and private partnership in urban design
      - Regulation and its role in shaping urban design
      - Property rights and their impact on urban design decision-making
      - Incentives and disincentives: direct and indirect approaches
      - Information as a tool for effective urban design policy
      - Choosing the right tools and designing effective urban design programs

  - Case Study 1: Downtown Planning in San Francisco:
    sections:
      - The history and evolution of downtown planning in San Francisco
      - Analyzing successful urban design projects in downtown San Francisco
      - Challenges and lessons learned from past downtown planning initiatives
      - Field trip to Boston Civic Design Commission meeting: Understanding the practical application of urban design policy

  - Case Study 2: Design Review:
    sections:
      - Exploring the concept of design review in urban design policy
      - Understanding the role of design review boards and committees
      - Analyzing design review processes and their effectiveness
      - Case studies of successful design review projects

  - Conclusion:
    sections:
      - Recap of key concepts and topics covered in the textbook
      - Reflecting on the importance of urban design policy and action
      - Future trends and challenges in urban design policy
      - Inspiring students to engage in urban design policy and action

Note: The above table of contents is a detailed expansion of the original syllabus, providing additional information and subtopics to create a comprehensive guide for the course.