```yaml
textbook:
  Transport Processes in the Environment: A Comprehensive Guide
  chapters:
    - Chapter 1: Introduction to Transport Processes
      sections:
        - Section 1.1: Conceptual Model of Diffusion
          subsections:
            - Subsection 1.1.1: Random Walk Animation
            - Subsection 1.1.2: Problems and Solutions
        - Section 1.2: Conservation of Mass
          subsections:
            - Subsection 1.2.1: Total Derivative Animations
            - Subsection 1.2.2: Problems and Solutions
    - Chapter 2: Diffusion of Substances in the Environment
      sections:
        - Section 2.1: Diffusion of an Instantaneous Point Release
          subsections:
            - Subsection 2.1.1: Animation of Anisotropic Diffusion of a Point Release
            - Subsection 2.1.2: Problems and Solutions
        - Section 2.2: Boundary Conditions
          subsections:
            - Subsection 2.2.1: Animation Comparing No-Flux and Absorbing Boundaries
            - Subsection 2.2.2: Problems and Solutions
        - Section 2.3: Advection and Diffusion of an Instant
          subsections:
            - Subsection 2.3.1: Animation Showing Simultaneous Advection and Diffusion
            - Subsection 2.3.2: Animation of a Continuous Source Discharging into a Uniform Flow
    - Chapter 3: Uncertainty in Transport Processes
      sections:
        - Section 3.1: Sources of Uncertainty
          subsections:
            - Subsection 3.1.1: Relative Humidity
            - Subsection 3.1.2: Reactor Models
            - Subsection 3.1.3: Residence Time Distribution
        - Section 3.2: Propagation of Error in Velocity Measurements
          subsections:
            - Subsection 3.2.1: Introduction to Diffusion
            - Subsection 3.2.2: Differential Form of Transport Equation
    - Chapter 4: Laboratory Experiments on Transport Processes
      sections:
        - Section 4.1: Wetland Circulation Residence Time
          subsections:
            - Subsection 4.1.1: Lab 3: Nepf Wetland Circulation Residence Time
        - Section 4.2: Dispersion in Soil Column
          subsections:
            - Subsection 4.2.1: Lab 4: Nepf Dispersion in Soil Column
        - Section 4.3: Flume Tracer Study Diffusivity/Dispersion
          subsections:
            - Subsection 4.3.1: Lab 6: Nepf Flume Tracer Study Diffusivity/Dispersion
```
```