textbook:
  Urban Design: Past, Present, and Future
  chapters:
    - Urban Design Now:
        sections:
          - Designing Places and Policies
          - Assessing the Current State of Urban Design
          - Urban Design Competitions and How to Judge Them
    - Evaluating Urban Design:
        sections:
          - Discussion of Assignment 1
          - Evaluating the Success of Urban Design Projects
          - Measuring the Impact of Urban Design on Communities
    - Assessing Urban Design Futures:
        sections:
          - Past Futures
          - Inventing New Ways of Living: Homes and Neighborhoods
            subsections:
              - The Role of Architecture in Urban Design
              - Sustainable Housing Solutions
              - Community Engagement in Neighborhood Planning
          - Distributing Work: The New Workplace
            subsections:
              - The Role of Technology in Remote Work
              - Designing Collaborative Workspaces
              - Addressing Inequality in Access to Workplaces
          - The Advent of 'Mediated' Space: Public Places and Technology
            subsections:
              - The Impact of Technology on Public Spaces
              - Smart Cities and Urban Connectivity
              - Designing Inclusive Public Spaces
          - Creating a City of Learning: Schools and Stories in the City
            subsections:
              - The Role of Education in Urban Design
              - Designing Learning Environments
              - Incorporating Local History and Culture in Urban Education
          - Reclaiming the Industrial landscape: Land and Water Infrastructure
            subsections:
              - Adaptive Reuse of Industrial Sites
              - Sustainable Water Management in Urban Areas
              - Revitalizing Waterfronts and Industrial Zones
          - Rediscovering Nature: Natural Systems in the City
            subsections:
              - Urban Green Spaces and Parks
              - Biodiversity Conservation in Urban Areas
              - Integrating Nature into Urban Design
          - What Have We Missed?
            subsections:
              - Emerging Trends in Urban Design
              - Case Studies of Innovative Urban Design Projects
          - Redesigning Urban Design
            subsections:
              - Rethinking Urban Design Principles
              - Collaborative Approaches to Urban Planning and Design