course:
  Physics for Solid-State Applications Textbook:
    chapters:
    - Introduction to Solid-State Physics:
        sections:
        - Molecules - the Simple Solid
        - Vibrational and Rotational States in Hydrogen
        - Metal as a Free Electron Gas
        - Vibrations in Solids
        - Specific Heat of Lattice Waves
        subsections: []
    - Lattice Waves in 1D Crystals:
        sections:
        - Lattice Waves in 1D Monatomic Crystals
        - Lattice Waves in 1D with Diatomic Basis
        - Specific Heat of Discrete Lattice
        subsections: []
    - Electrons in Periodic Solids:
        sections:
        - Electrons in a Periodic Solid
        - Nearly Free Electron Bands
        - Properties of Bloch Functions
        - Motion of Electronic Wavepackets
        - Impurity States
        - Semi Classical Equations of Motion and Electrons and Holes I
        subsections: []
    - Effective Mass and Equilibrium:
        sections:
        - Effective Mass
        - Chemical Potential and Equilibrium
        - Chemical Potential and Non-equilibrium
        - Inhomogeneous Solids
        - Scattering of Bloch Functions
        - Electron-Phonon Scattering
        subsections: []
    - Semiconductor Projects:
        sections:
        - Physical Structure of a Semiconductor
        - Phonon Spectra of a Semiconductor
        - Band Structure of a Semiconductor
        subsections: []