textbook:
  Introduction to Environmental Policy and Planning: A Comprehensive Guide
  chapters:
    - Introduction:
        sections:
        - What do environmental planners do?
        - Connection between environmental planning and environmental policy-making
        - Review of course objectives
        - Socratic approach used in the class
        - Student responsibilities and grading policy
        - Indicators of the success of an environmental policy
    - 'Chapter 1: Formulation and Implementation of Environmental Policies':
        sections:
        - The Policy-Making Process
        - Policy Evaluation
        - Comparative Policy Analysis
        - A Theory of Environmental Planning and Policy-Making
        - Environmental Ethics
        - Utilitarianism vs. Deep Ecology
        - Sustainability vs. Economic Growth
        - Scientific Expertise vs. Indigenous Knowledge
        - 'Environmental Analysis: Science, Policy, and Politics in Environmental Decision-Making'
        - Environmental Impact Assessment
        - Cost-Benefit Analysis
        - Risk Assessment
        - Humboldt Game Simulation Role Play
        - Ecosystem Services Analysis
        - Simulation and Modeling
        - Scenario Planning
        - Public Participation and Group Decision-Making
        - Public Participation Timelines
        - Collaborative Decision-Making
        - Consensus Building and Dispute Resolution
        - Politics, Power, and Theories of Collective Action