book:
  Introduction to Architecture & Environmental Design: A Comprehensive Guide
  chapters:
    - A Trans-Scalar Practice:
        sections:
        - Scale and Proportion
            subsections:
            - Understanding Scale in Architecture
            - Principles of Proportion in Design
        - Rhythm in Architecture
            subsections:
            - Creating Rhythm through Repetition
            - The Role of Rhythm in Architectural Composition
    - 'The Human Scale: Bauhaus/Eames':
        sections:
        - Body Measurements
            subsections:
            - Anthropometry in Architecture
            - Ergonomics and Human Factors in Design
        - Drawing Wire
            subsections:
            - Techniques for Drawing to Scale
            - Using Wireframes in Architectural Representation
        - Building Wire
            subsections:
            - Structural Systems and Construction Techniques
            - Wireframe Modeling in Architectural Design
    - 'The Post-Human: Fuller/Archigram/Cedric Price':
        sections:
        - Review Assignment 1.3
            subsections:
            - Analysis of Post-Human Architecture
            - Critique of Fuller, Archigram, and Cedric Price's Works
    - 'The Domestic Scale: Villas':
        sections:
        - Review Assignment 1.4
            subsections:
            - Study of Domestic Architecture
            - Analysis of Villa Design Principles
    - 'The Civic Scale: Bigness and Monumentality':
        sections:
        - Review Assignment 2.2
            subsections:
            - Understanding Bigness in Architecture
            - Exploring Monumentality in Urban Design
    - 'The Neighborhood: The Urban Project':
        sections:
        - Final Review
            subsections:
            - Urban Planning and Design Process
            - Case Studies of Successful Urban Projects
    - Exercises 1 and 2:
        sections:
        - Sample Student Work
            subsections:
            - Example Projects for Exercises 1 and 2
            - Analysis and Feedback on Student Work
    - Exercise 3:
        sections:
        - Sample Student Work
            subsections:
            - Example Projects for Exercise 3
            - Analysis and Feedback on Student Work