textbook:
  Chemical Investigations of Boston Harbor: A Comprehensive Guide
  chapters:
    - Physical Oceanography:
        sections:
        - The Oceans in Motion:
            subsections: []
        - Historical Perspective on Sampling Equipment for Oceanic Research:
            subsections: []
    - Nutrient Cycles:
        sections:
        - Nutrient Cycles and Ecosystem Stoichiometry:
            subsections: []
    - Carbon Cycle:
        sections:
        - The Carbon Cycle: Production and Transformations of Organic Matter:
            subsections: []
    - Marine Bioinorganic Chemistry:
        sections:
        - The Role of Trace Metals in the Oceanic Cycles of Major Nutrients:
            subsections: []
    - Chemical Sensors in Marine Science:
        sections:
        - Chemical Sensors in Marine Science:
            subsections: []
    - Field Trip to Boston Harbor/ Buzzards Bay:
        sections:
        - Field Trip to Boston Harbor/ Buzzards Bay:
            subsections: []
    - Physical Parameters of The Coastal Ocean:
        sections:
        - Physical Parameters of The Coastal Ocean:
            subsections: []
    - Biological Productivity:
        sections:
        - Biological Productivity:
            subsections: []
    - Electronic Components and Power Sources for Oceanographic Systems:
        sections:
        - Electronic Components and Power Sources for Oceanographic Systems:
            subsections: []
    - 'WHOI Tour 1: WHOI’s Chemical Instrumentation Facilities':
        sections:
        - 'WHOI Tour 1: WHOI’s Chemical Instrumentation Facilities':
            subsections: []