course:
  Environmental Justice Law and Policy Textbook:
    chapters:
      - Introduction, Theories, and Histories of Environmental Justice:
          sections:
            - Founding Documents of Environmental Justice
            - Histories of the Environmental Justice Movement
      - Theories of Environmental Justice:
          sections:
            - Critical Race Theory
            - Environmental Racism
            - Distributive Justice
            - Procedural Justice
      - Causation:
          sections:
            - Proximate and Ultimate Causes
            - Cumulative Impacts
            - Environmental Injustice
            - Environmental Displacement
      - Environmental Impact Assessment:
          sections:
            - Purpose and Process of EIA
            - Stakeholder Engagement in EIA
            - Environmental Justice in EIA
            - Case Studies of EIA in Environmental Justice
      - Site Cleanup and Enforcement:
          sections:
            - Superfund Program
            - Brownfields
            - Remediation Technologies
            - Community Involvement in Site Cleanup
      - 'Advancing Environmental Justice: Risk, Regulation, Information':
          sections:
            - Risk Assessment and Management
            - Environmental Regulations and Policies
            - Environmental Data and Information Access
            - Environmental Justice and Public Health
      - Standard-Setting:
          sections:
            - Environmental Standards and Guidelines
            - Environmental Justice in Standard-Setting
            - Regulatory Impact Analysis
      - Federal Responses:
          sections:
            - Federal Agencies and Environmental Justice
            - Environmental Justice Executive Order
            - Title VI of the Civil Rights Act
      - The Production of Environmental Knowledge:
          sections:
            - Scientific Research and Environmental Justice
            - Indigenous Knowledge and Environmental Justice
            - Citizen Science and Environmental Justice
            - Environmental Justice in Academic Institutions
      - Risk, Regulation, and Environmental Justice:
          sections:
            - Environmental Justice and Risk Assessment
            - Precautionary Principle and Environmental Justice
            - Environmental Justice and Regulatory Enforcement
            - Environmental Justice and Environmental Governance
      - Environmental Justice Movements and Activism:
          sections:
            - Grassroots Environmental Justice Organizations
            - International Environmental Justice Movements
            - Youth Activism and Environmental Justice
            - Intersectionality in Environmental Justice
      - Environmental Justice and Climate Change:
          sections:
            - Climate Justice and Equity
            - Adaptation and Resilience in Environmental Justice
            - Mitigation and Environmental Justice
      - Environmental Justice and Indigenous Rights:
          sections:
            - Indigenous Environmental Justice Frameworks
            - Land Rights and Environmental Justice
            - Indigenous Sovereignty and Environmental Justice
      - Environmental Justice and Food Justice:
          sections:
            - Food Systems and Environmental Justice
            - Food Insecurity and Environmental Justice
            - Food Sovereignty and Environmental Justice
      - Environmental Justice and Water Rights:
          sections:
            - Water Access and Environmental Justice
            - Water Pollution and Environmental Justice
            - Water Privatization and Environmental Justice
      - Environmental Justice and Energy Policy:
          sections:
            - Energy Justice and Equity
            - Renewable Energy and Environmental Justice
            - Fossil Fuels and Environmental Justice
      - Environmental Justice and Urban Planning:
          sections:
            - Environmental Justice in Urban Development
            - Gentrification and Environmental Justice
            - Transit Equity and Environmental Justice
      - Environmental Justice and Environmental Education:
          sections:
            - Environmental Justice in K-12 Education
            - Environmental Justice in Higher Education
            - Environmental Justice and Environmental Literacy