```yaml
textbook:
  Network and Computer Security: A Comprehensive Guide
    chapters:
    - Introduction:
        sections:
        - Course Number
        - Course Name
        - Resource Level
    - Security Mechanisms and Principles:
        sections:
        - Security Mechanisms
        - Security Principles
    - Encryption and Perfect Secrecy:
        sections:
        - Encryption
        - Perfect Secrecy
        - One-Time Pad
    - Cryptographic Hash Functions:
        sections:
        - Hash Functions
        - Cryptographic Hash Functions
    - Hashing Applications and Constructions:
        sections:
        - Hashing Applications
        - Hashing Constructions
    - Bitcoin:
        sections:
        - Bitcoin Overview
    - Secret Sharing:
        sections:
        - Secret Sharing
    - Block Ciphers:
        sections:
        - Block Ciphers
    - Block Cipher Modes:
        sections:
        - Block Cipher Modes
    - Message Authentication Codes:
        sections:
        - Message Authentication Codes
    - Prime Finding and Crypto Math:
        sections:
        - Prime Finding
        - Crypto Math
    - Diffie-Hellman Key Exchange:
        sections:
        - Diffie-Hellman Key Exchange
        - Crypto Groups
    - Pedersen Commitment:
        sections:
        - Pedersen Commitment
        - PK Encryption
        - DDH
    - Malleability of El Gamal:
        sections:
        - Malleability of El Gamal
        - IND-CCA2
    - Digital Signatures:
        sections:
        - Digital Signatures
        - DSA
        - Gap Groups
    - Gap Groups and Bilinear Maps:
        sections:
        - Gap Groups
        - Bilinear Maps
        - Applications
    - Zero-Knowledge Proofs:
        sections:
        - Zero-Knowledge Proofs
    - Security of Voting:
        sections:
        - Security of Voting
    - Project Presentations:
        sections:
        - Project Presentations
    - No Class:
        sections:
        - No Class
```