textbook:
  Science, Politics, and Environmental Policy: A Comprehensive Guide
  
chapters:
  - What is Science?:
    sections:
      - Introduction to the Course
      - The Policy Process and the Political Debate Over 'Sound Science'
      - The Scientific Method and the Production of Scientific Knowledge
  - Environmental Science:
    sections:
      - Environmental Advocacy: Using Science to Define Problems
      - Media Coverage of Science and Environmental Risk
      - The Public's Perception of Science and Environmental Risk
  - Science in Decision Making:
    sections:
      - Science in Legislative Decision Making
      - Science in Administrative and Judicial Decision Making
      - Science in the International Arena
  - Advocacy Science vs. Collaborative Science:
    sections:
      - Advocacy Science vs. Collaborative Science
      - Local Knowledge
      - Uncertainty, Adaptive Management and the Precautionary Principle
  - Other Topics:
    sections:
      - (Add additional topics and subtopics as needed)