```
textbook:
  U.S. Budgets for National Security: A Comprehensive Analysis
  chapters:
    - Introduction - Budgets as Policy:
      sections:
        - Money is Policy
        - Understanding the Federal Budget
    - National Security Budgets in Context:
      sections:
        - Composition of the Defense Budget
        - Internal Pressures and Influences on Budgets
        - Budgetary Constraints and Political Considerations
    - Grand Strategy and Budgets:
      sections:
        - Planning and Budgeting for National Security
        - Allocating Funds for Military Pay and Benefits
        - Balancing Priorities: Trade-offs and Challenges
    - Budgets to Modernize the Force:
      sections:
        - Modernization Budgets and Technological Advancements
        - Operation and Maintenance Budgets for Sustaining Readiness
        - Evaluating Efficiency and Effectiveness of Budget Allocation
    - Cost of the War in Iraq:
      sections:
        - Understanding the Economic Impact of the War
        - Assessing the Financial Burden on National Security Budgets
    - Federal Spending for Homeland Security:
      sections:
        - Analyzing Homeland Security Budgets and Priorities
        - Assessing the Effectiveness of Homeland Security Investments
    - Federal Spending for Diplomacy and Foreign Aid:
      sections:
        - Diplomacy Budgets and Priorities
        - Foreign Aid Budgets and Their Impact on National Security
        - Evaluating the Effectiveness of Diplomatic Efforts
    - Presentation of Alternative National Security Plans:
      sections:
        - Analyzing Alternative Plans and Their Policy Implications
        - Comparisons of Different Approaches to National Security
        - Evaluating the Feasibility and Impacts of Alternative Plans
```
