textbook:
  International Politics and Climate Change: A Comprehensive Guide
  chapters:
    - 'Chapter 1: Introduction: systems and complexities':
        sections:
        - 'Section 1.1: The legacies of the 20th century'
        - 'Section 1.2: International politics of climate change'
        - 'Section 1.3: International relations theory'
    - 'Chapter 2: The global system - whole and parts':
        sections:
        - 'Section 2.1: Climate change science - core elements'
        - 'Section 2.2: Climate - political connections I - illustrative systems'
        - 'Section 2.3: Climate - political connections II - theoretical perspectives'
    - 'Chapter 3: International law and environmental regimes':
        sections:
        - 'Section 3.1: Global accord - comparative cases I and II'
        - 'Section 3.2: What next: highlights and conclusion'
    - 'Chapter 4: Contextualizing Climate Change':
        sections:
        - 'Section 4.1: Introduction: systems and complexities'
        - 'Section 4.2: The legacies of the 20th century'
        - 'Section 4.3: International politics of climate change'
        - 'Section 4.4: International relations theory'
    - 'Chapter 5: Climate Science and Policy':
        sections:
        - 'Section 5.1: The global system - whole and parts'
        - 'Section 5.2: Climate change science - core elements'
        - 'Section 5.3: Climate - political connections I - illustrative systems'
        - 'Section 5.4: Climate - political connections II - theoretical perspectives'
        - 'Section 5.5: International law and environmental regimes'
    - 'Chapter 6: Comparative Climate Politics':
        sections:
        - 'Section 6.1: Global accord - comparative cases I and II'
        - 'Section 6.2: What next: highlights and conclusion'
    - 'Chapter 7: Climate Change and Security':
        sections:
        - 'Section 7.1: Introduction: systems and complexities'
        - 'Section 7.2: The legacies of the 20th century'
        - 'Section 7.3: International politics of climate change'
        - 'Section 7.4: International relations theory'
        - 'Section 7.5: The global system - whole and parts'
    - 'Chapter 8: Climate Change Governance and Diplomacy':
        sections:
        - 'Section 8.1: Climate change science - core elements'
        - 'Section 8.2: Climate - political connections I - illustrative systems'
        - 'Section 8.3: Climate - political connections II - theoretical perspectives'
        - 'Section 8.4: International law and environmental regimes'
        - 'Section 8.5: Global accord - comparative cases I and II'
    - 'Chapter 9: Climate Change and Global Justice':
        sections:
        - 'Section 9.1: What next: highlights and conclusion'
        - 'Section 9.2: Introduction: systems and complexities'
        - 'Section 9.3: The legacies of the 20th century'
        - 'Section 9.4: International politics of climate change'
        - 'Section 9.5: International relations theory'
        - 'Section 9.6: The global system - whole and parts'
        - 'Section 9.7: Climate change science - core elements'
    - 'Chapter 10: Climate Change and Development':
        sections:
        - 'Section 10.1: Climate - political connections I - illustrative systems'
        - 'Section 10.2: Climate - political connections II - theoretical perspectives'
        - 'Section 10.3: International law and environmental regimes'
        - 'Section 10.4: Global accord - comparative cases I and II'
        - 'Section 10.5: What next: highlights and conclusion'