```yaml
course:
  Applications of Continuum Mechanics to Earth, Atmospheric, and Planetary Sciences:
    textbook:
      title: "Continuum Mechanics for Earth, Atmospheric, and Planetary Sciences"
      chapters:
        - Chapter 1: Introduction to Continuum Mechanics
          sections:
            - Section 1.1: Fundamentals of Continuum Mechanics
            - Section 1.2: Continuum Approximation in Earth Sciences
            - Section 1.3: Continuum Approximation in Atmospheric Sciences
            - Section 1.4: Continuum Approximation in Planetary Sciences
        - Chapter 2: Traction and Stress Analysis
          sections:
            - Section 2.1: Definition of Traction
            - Section 2.2: Normal and Shear Traction
            - Section 2.3: Traction Vector
            - Section 2.4: Stress Tensor
            - Section 2.5: Components of Stress Tensor
            - Section 2.6: Stress in Different Coordinate Systems
        - Chapter 3: Pore Fluid Pressure and Its Effects
          sections:
            - Section 3.1: Definition of Pore Fluid Pressure
            - Section 3.2: Effect of Pore Fluid Pressure on Stress Distribution
            - Section 3.3: Fluid Pressure in Porous Media
        - Chapter 4: Equations of Motion and Conservation Laws
          sections:
            - Section 4.1: Newton's Second Law
            - Section 4.2: Conservation of Momentum
            - Section 4.3: Forces Acting on a Body
        - Chapter 5: Stress Analysis in the Earth
          sections:
            - Section 5.1: Stress Distribution in the Earth
            - Section 5.2: Lithospheric Stress
            - Section 5.3: Tectonic Stress
        - Chapter 6: Stress Rotation and Mohr's Circle
          sections:
            - Section 6.1: Transformations of Stress Tensor
            - Section 6.2: Principal Stresses and Directions
            - Section 6.3: Mohr's Circle
        - Chapter 7: Sandbox Tectonics and Experimental Models
          sections:
            - Section 7.1: Experimental Models of Tectonic Processes
            - Section 7.2: Scaling Laws in Sandbox Experiments
            - Section 7.3: Tectonic Deformation Patterns
        - Chapter 8: Displacement Gradients and Strain Analysis
          sections:
            - Section 8.1: Definition of Displacement Gradient
            - Section 8.2: Strain Tensor
            - Section 8.3: Deformation Gradient
        - Chapter 9: Techniques for Measuring Displacement Gradient
          sections:
            - Section 9.1: Introduction to Measurement of Displacement Gradient
            - Section 9.2: Image Velocimetry
            - Section 9.3: Strain Gauges
        - Chapter 10: Finite Strain Analysis
          sections:
            - Section 10.1: Large Deformation Theory
            - Section 10.2: Green-Lagrange Strain Tensor
            - Section 10.3: Compatibility Equations
        - Chapter 11: Elasticity and Elastic Moduli
          sections:
            - Section 11.1: Hooke's Law
            - Section 11.2: Elastic Moduli
            - Section 11.3: Elasticity Tensor
        - Chapter 12: Example: Uniaxial Strain and Young's Modulus
          sections:
            - Section 12.1: One-Dimensional Strain
            - Section 12.2: Stress-Strain Relationship
            - Section 12.3: Young's Modulus
        - Chapter 13: Special Cases of Strain Analysis
          sections:
            - Section 13.1: Plane Strain
            - Section 13.2: Plane Stress
            - Section 13.3: Axisymmetric Deformation
        - Chapter 14: Dislocation Theory and Earthquake Cycle
          sections:
            - Section 14.1: Fault Slip
            - Section 14.2: Earthquake Rupture
            - Section 14.3: Aseismic Slip
        - Chapter 15: Stress and Strain Analysis from Dislocation
          sections:
            - Section 15.1: Dislocation Theory
            - Section 15.2: Burgers Vector
            - Section 15.3: Dislocation Line
        - Chapter 16: Plate Tectonics and Boundaries
          sections:
            - Section 16.1: Plate Tectonics
            - Section 16.2: Plate Boundaries
            - Section 16.3: Plate Motions
        - Chapter 17: Plate Tectonics Overview and Rheology
          sections:
            - Section 17.1: Plate Tectonics Overview
            - Section 17.2: Plate Boundary Interactions
            - Section 17.3: Rheology of the Lithosphere
        - Chapter 18: Fluid Properties and Equations
          sections:
            - Section 18.1: Fluid Properties
            - Section 18.2: Continuity Equation
            - Section 18.3: Bernoulli's Equation
        - Chapter 19: Fluid Flow and Navier-Stokes Equation
          sections:
            - Section 19.1: Governing Equations for Fluid Flow
            - Section 19.2: Incompressible Flow
            - Section 19.3: Viscous Effects
        - Chapter 20: Growth, Decay, and Surface Instabilities
          sections:
            - Section 20.1: Linear Stability Analysis
            - Section 20.2: Growth and Decay Rates
            - Section 20.3: Surface Instabilities
        - Chapter 21: Fluid Flow in Porous Media
          sections:
            - Section 21.1: Darcy's Law
            - Section 21.2: Permeability
            - Section 21.3: Fluid Flow in Sedimentary Basins
        - Chapter 22: Time Dependent Porous Flow
          sections:
            - Section 22.1: Transient Flow
            - Section 22.2: Diffusion Equation
            - Section 22.3: Boundary Conditions
      subsubtopics:
        - Subsection 1.1.1: Introduction to Continuum Mechanics
        - Subsection 1.1.2: Continuum Approximation in Earth Sciences
        - Subsection 1.1.3: Continuum Approximation in Atmospheric Sciences
        - Subsection 1.1.4: Continuum Approximation in Planetary Sciences
        - Subsection 2.4.1: Definition of Stress Tensor
        - Subsection 2.4.2: Components of Stress Tensor
        - Subsection 2.4.3: Stress in Different Coordinate Systems
        - Subsection 3.1.1: Definition of Pore Fluid Pressure
        - Subsection 3.1.2: Effect of Pore Fluid Pressure on Stress Distribution
        - Subsection 3.1.3: Fluid Pressure in Porous Media
        - Subsection 4.1.1: Newton's Second Law
        - Subsection 4.1.2: Conservation of Momentum
        - Subsection 4.1.3: Forces Acting on a Body
        - Subsection 5.1.1: Stress Distribution in the Earth
        - Subsection 5.1.2: Lithospheric Stress
        - Subsection 5.1.3: Tectonic Stress
        - Subsection 6.1.1: Transformations of Stress Tensor
        - Subsection 6.1.2: Principal Stresses and Directions
        - Subsection 6.1.3: Mohr's Circle
        - Subsection 7.1.1: Experimental Models of Tectonic Processes
        - Subsection 7.1.2: Scaling Laws in Sandbox Experiments
        - Subsection 7.1.3: Tectonic Deformation Patterns
        - Subsection 8.1.1: Definition of Displacement Gradient
        - Subsection 8.1.2: Strain Tensor
        - Subsection 8.1.3: Deformation Gradient
        - Subsection 9.1.1: Introduction to Measurement of Displacement Gradient
        - Subsection 9.1.2: Image Velocimetry
        - Subsection 9.1.3: Strain Gauges
        - Subsection 10.1.1: Large Deformation Theory
        - Subsection 10.1.2: Green-Lagrange Strain Tensor
        - Subsection 10.1.3: Compatibility Equations
        - Subsection 11.1.1: Hooke's Law
        - Subsection 11.1.2: Elastic Moduli
        - Subsection 11.1.3: Elasticity Tensor
        - Subsection 12.1.1: One-Dimensional Strain
        - Subsection 12.1.2: Stress-Strain Relationship
        - Subsection 12.1.3: Young's Modulus
        - Subsection 13.1.1: Plane Strain
        - Subsection 13.1.2: Plane Stress
        - Subsection 13.1.3: Axisymmetric Deformation
        - Subsection 14.1.1: Fault Slip
        - Subsection 14.1.2: Earthquake Rupture
        - Subsection 14.1.3: Aseismic Slip
        - Subsection 15.1.1: Dislocation Theory
        - Subsection 15.1.2: Burgers Vector
        - Subsection 15.1.3: Dislocation Line
        - Subsection 16.1.1: Plate Tectonics
        - Subsection 16.1.2: Plate Boundaries
        - Subsection 16.1.3: Plate Motions
        - Subsection 17.1.1: Plate Tectonics Overview
        - Subsection 17.1.2: Plate Boundary Interactions
        - Subsection 17.1.3: Rheology of the Lithosphere
        - Subsection 18.1.1: Fluid Properties
        - Subsection 18.1.2: Continuity Equation
        - Subsection 18.1.3: Bernoulli's Equation
        - Subsection 19.1.1: Governing Equations for Fluid Flow
        - Subsection 19.1.2: Incompressible Flow
        - Subsection 19.1.3: Viscous Effects
        - Subsection 20.1.1: Linear Stability Analysis
        - Subsection 20.1.2: Growth and Decay Rates
        - Subsection 20.1.3: Surface Instabilities
        - Subsection 21.1.1: Darcy's Law
        - Subsection 21.1.2: Permeability
        - Subsection 21.1.3: Fluid Flow in Sedimentary Basins
        - Subsection 22.1.1: Transient Flow
        - Subsection 22.1.2: Diffusion Equation
        - Subsection 22.1.3: Boundary Conditions

```