textbook:
  Environment and Society: A Comprehensive Guide
  chapters:
  - Introduction to the Course:
      sections:
      - Course Number
      - Course Name
      - Resource Level
  - State of the Environment:
      sections:
      - Challenges of the New Century
      - Anticipating Environmental 'Surprise'
      subsections:
      - Climate Change and its Impacts
      - Pollution and its Effects
  - Readings:
      sections:
      - No Readings
  - Assignments:
      sections:
      - The class will involve considerable reading each week
      - Class participation
      - Several short assignments
      - Term paper and presentation
      - Turn in bio
      subsections:
      - Research and Writing Skills
      - Presentation Techniques
  - Projects:
      sections:
      - No Readings
  - Exams:
      sections:
      - No Readings
  - Syllabus:
      sections:
      - Information
  - Calendar:
      sections:
      - 'Please note: Reading locations are noted below as: available as Books (B)
        at the COOP; in the Reader (R); or on the Web (W)'
      subsections:
      - Course Schedule
      - Important Dates