```yaml
textbook:
  'Photography as Inquiry: Exploring Landscape through the Lens':
    chapters:
    - Chapter 1: Reading and Telling Landscape
        sections:
        - Section 1.1: The Language of Landscape
            subsections:
            - Spirn, Anne Whiston. The Language of Landscape. Yale, 1998.
            - Spirn. Language of Landscape. Pp. 3-81.
        - Section 1.2: Exploring the Nature of Cities
            subsections:
            - Meyerowitz, Joel. 'Nature of Cities.'
            - Meinig, D. W., ed. The Interpretation of Ordinary Landscapes. Oxford, 1979.
        - Section 1.3: Landscape Narratives and Visual Storytelling
            subsections:
            - Potteiger, Matthew, and Jamie Purinton. Landscape Narratives. Wiley, 1998.
            - Watts, May. Reading the Landscape of America. Collier, 1975.
            - Cronon, William. 'A Place for Stories: Nature, History, and Narrative.' Journal of A
            - Spirn, Anne Whiston. 'Reading the Landscape: An Invitation to Grounded Viewing.'
    - Chapter 2: Site Selection
        sections:
        - Section 2.1: Factors Influencing Site Selection
            subsections:
            - Due by 5PM
        - Section 2.2: Researching and Evaluating Potential Sites
            subsections:
            - Conducting Field Surveys
            - Analyzing Geographical Data
            - Considering Cultural and Historical Significance
        - Section 2.3: Case Studies in Effective Site Selection
            subsections:
            - Examining Successful Photography Projects
            - Learning from Failed Site Selections
    - Chapter 3: Understanding Light in Photography
        sections:
        - Section 3.1: The Science of Light
            subsections:
            - The Behavior of Light Waves
            - The Electromagnetic Spectrum
        - Section 3.2: Capturing Light: Camera Settings and Techniques
            subsections:
            - Aperture and Depth of Field
            - Shutter Speed and Motion Blur
            - ISO and Sensitivity
        - Section 3.3: The Art of Light: Manipulating Natural and Artificial Light
            subsections:
            - Golden Hour and Blue Hour Photography
            - Lighting Equipment and Techniques
        - Section 3.4: Light Assignment: Applying Light Principles in Practice
            subsections:
            - Light Assignment due in class.
    - Chapter 4: Framing the Shot: Knowing Where to Stand
        sections:
        - Section 4.1: Framing and Composition Techniques
            subsections:
            - Rule of Thirds
            - Leading Lines
            - Symmetry and Balance
        - Section 4.2: Exploring Unique Perspectives
            subsections:
            - Aerial Photography
            - Macro Photography
            - Underwater Photography
        - Section 4.3: Exhibition Opening: Compton Gallery
            subsections:
            - Exhibit opening 5:30-7:30.
    - Chapter 5: Elements of Landscape Language
        sections:
        - Section 5.1: Understanding Visual Elements
            subsections:
            - Line and Shape
            - Color and Tone
            - Texture and Pattern
        - Section 5.2: Composition and Visual Hierarchy
            subsections:
            - Balance and Symmetry
            - Contrast and Emphasis
            - Rhythm and Movement
        - Section 5.3: The Power of Negative Space
            subsections:
            - Using Negative Space for Impact
            - Creating Depth and Dimension
    - Chapter 6: Capturing Significant Detail
        sections:
        - Section 6.1: Recognizing and Isolating Detail
            subsections:
            - Macro Photography Techniques
            - Selective Focus and Depth of Field
        - Section 6.2: Detail Assignment: Emphasizing the Small
            subsections:
            - Detail Assignment due in class.
    - Chapter 7: Exploring the Context of Place
        sections:
        - Section 7.1: Historical and Cultural Context
            subsections:
            - Researching Local History and Traditions
            - Identifying Cultural Signifiers in the Landscape
        - Section 7.2: Environmental and Ecological Context
            subsections:
            - Understanding Ecosystems and Biodiversity
            - Documenting Human Impact on the Environment
        - Section 7.3: Field Trip: Exploring Nahant
            subsections:
            - There will be an all-day field trip to Nahant. We will combine an overview of digital printing in the studio and shooting along the shores of Massachusetts Bay and Boston Harbor.
    - Chapter 8: Landscapes and Poetics
        sections:
        - Section 8.1: Finding Inspiration in Nature
            subsections:
            - The Sublime in Landscape Photography
            - Translating Emotions into Visual Language
        - Section 8.2: Abstract and Experimental Approaches
            subsections:
            - Intentional Camera Movement (ICM)
            - Multiple Exposures and Blending Techniques
        - Section 8.3: Poetry Reading: Exploring the Intersection of Text and Image
            subsections:
            - Analyzing Poems Inspired by Landscapes
            - Creating Visual Responses to Poetry
    - Chapter 9: Images and Words: Creating a Visual Narrative
        sections:
        - Section 9.1: Visual Storytelling Techniques
            subsections:
            - Sequential Photography
            - Montage and Collage
            - Diptychs and Triptychs
        - Section 9.2: Writing About Photography: Crafting Captions and Artist Statements
            subsections:
            - Conveying Intention and Meaning
            - Engaging the Viewer through Words
        - Section 9.3: Individual Student Meetings: Reviewing Photo Essays
            subsections:
            - Landscape Narratives
            - Meetings with Individual Students
            - Review of Photo Essays in Online Galleries
```