textbook:
  Quantum Physics and Urban Design: Exploring the Intersections of Science and the Built Environment
  chapters:
    - Basic Features of Quantum Mechanics:
        sections:
        - Linearity
        - Complex Numbers
        - Non-deterministic
        - Superposition
        - Entanglement
    - Experimental Basis of Quantum Physics:
        sections:
        - Two-slit Experiments
        - Mach-Zehnder Interferometer
        - Elitzur-Vaidman Bombs
        - Photoelectric Effect
        - Compton Scattering
        - de Broglie Wavelength
    - Wave Mechanics:
        sections:
        - Galilean Transformation of de Broglie Wavelength
        - Wave-packets and Group Velocity
        - Matter Wave for a Particle
        - Momentum and Position Operators
        - Schrödinger Equation
    - Interpretation of the Wavefunction:
        sections:
        - Probability Density
        - Probability Current
        - Current Conservation
        - Hermitian Operators
    - Expectation Values and Uncertainty:
        sections:
        - Expectation Values of Operators
        - Time Evolution of Wave-packets
        - Fourier Transforms
        - Parseval Theorem
        - Uncertainty Relation
    - Quantum Physics in One-dimensional Potentials:
        sections:
        - Stationary States
        - Boundary Conditions
        - Particle on a Circle
        - Infinite Square Well
        - Finite Square Well
        - Semiclassical Approximations
        - Numerical Solution by the Shooting Method
        - Delta Function Potential
        - Simple Harmonic Oscillator
        - Reflection and Transmission Coefficients
        - Ramsauer Townsend Effect
        - 1D Scattering and Phase Shifts
        - Levinson’s Theorem
    - Angular Momentum and Central Potentials:
        sections:
        - Resonances and Breit-Wigner Distribution
        - Central Potentials
        - Algebra of Angular Momentum
        - Legendre Polynomials
        - Hydrogen Atom
        - Energy Levels Diagram
        - Virial Theorem
        - Circular Orbits and Eccentricity
        - Discovery of Spin
    - Urban Design:
        sections:
        - History of Urban Design
        - Urban Planning Principles
        - Public Space Design
        - Transportation Planning
        - Sustainability in Urban Design
        - Social and Cultural Factors in Urban Design
        - Urban Design and Architecture
        - Urban Design Case Studies
        - Participatory Urban Design Processes
        - Economic Considerations in Urban Design
        - Urban Design and Infrastructure
        - Urban Design and Public Health
        - Urban Design and Climate Change
        - Urban Design and Landscape Architecture
        - Urban Design and Technology
        - Urban Design and Community Development
        - Urban Design and Governance
        - Urban Design and Equity
        - Urban Design and Public Art
        - Urban Design and Historic Preservation