textbook:
  Integrated Chemical Engineering II: A Comprehensive Guide to Process Design, CO2 Capture, and Power Plant Retrofitting:
    chapters:
    - 'Chapter 1: Introduction: Global Climate and the CO2 Problem':
        sections:
        - Section 1.1: Course Overview and Process Design
        - Section 1.2: Literature Sources for Processes: How to Find Information
    - 'Chapter 2: Process Flowsheet Models':
        sections:
        - Section 2.1: An Introduction to AspenPlus®
        - Section 2.2: Reactor Modeling in AspenPlus®
        - Section 2.3: Introduction to Analysis Tools
    - 'Chapter 3: Process Engineering Economics':
        sections:
        - Section 3.1: Project Evaluation
        - Section 3.2: Capital Cost Estimates: Introduction to CAPCOST Software Program
    - 'Chapter 4: Physical Property Models':
        sections:
        - Section 4.1: Which One is Best?
    - 'Chapter 5: Combustion Basics':
        sections:
        - Section 5.1: How CO2 is Formed
    - 'Chapter 6: Evaluation of Alternative CO2 Removal Schemes':
        sections:
        - Section 6.1: Comparing Efficiencies
    - 'Chapter 7: Hierarchical Design Methodology':
        sections:
        - Section 7.1: Reactor Modeling
    - 'Chapter 8: Chemical Process Safety':
        sections:
        - Section 8.1: HAZOP Analyses
    - 'Chapter 9: Team Project Work':
        sections:
        - Section 9.1: Student Presentations
    - 'Chapter 10: Ammonia Stripping':
        sections:
        - Section 10.1: Assessment of the IGCC Concept
    - 'Chapter 11: Amine Stripping':
        sections:
        - Section 11.1: Retrofitting Options for CO2 Capture
        - Section 11.2: Amine Stripping Alternatives
    - 'Chapter 12: Retrofitting of Existing Power Plants':
        sections:
        - Section 12.1: Chemical Looping Combustion
        - Section 12.2: CO2 Liquefaction
        - Section 12.3: Oxyfiring
        - Section 12.4: Polygeneration
        - Section 12.5: Water Gas Shift Reaction
        - Section 12.6: Retrofitting of Existing Power Plants
        - Section 12.7: Chemical Looping Combustor