textbook:
  'Comprehensive Guide to Healthy Cities: Assessing Health Impacts of Policies and Plans':
    chapters:
    - Introduction to Healthy Cities:
        sections:
        - Course description
        - Understanding the Social Determinants of Health
        - Introduction to Rapid Health Impact Assessment (HIA) for Clients
    - Major Health Challenges:
        sections:
        - A Synopsis of Mortality and Morbidity Domestically and Abroad
        - Contrasting Perspectives on Health and Disease: A Global Perspective
        - The Interplay of Social Factors in Health Inequities
    - Rapid HIA:
        sections:
        - Training for Effective Rapid Health Impact Assessment
    - Health Disparities:
        sections:
        - Measurement, Definition, Monitoring, and Tracking of Health Disparities
        - Inequity versus Inequality: Understanding the Difference and Implications
        - Arguments for and Against a Focus on Narrowing Gaps in Health
        - Strategies for Addressing Health Disparities in Urban Settings
    - HIA Assessment:
        sections:
        - Introduction to Health Impact Assessment (HIA)
        - Key Steps and Components of a Comprehensive HIA
        - Best Practices for Implementing HIA in Policy and Planning
    - Criminal Justice System:
        sections:
        - Overview of the Criminal Justice System and Its Impacts on Health
        - Addressing Health Disparities in the Criminal Justice System
        - Promoting Health and Well-being in Correctional Facilities
    - Pathway Presentations:
        sections:
        - Presentation of Pathway Diagrams Demonstrating Links between Proposed Policies, Programs, or Projects, and Health Impacts
        - Analyzing Pathways for Health Equity: Methods and Case Studies
    - HIA Assessment Workshop:
        sections:
        - Health Impact Assessment of Record Expungement Policies
        - Assessing Health Impacts of Just Cause for Eviction Policies
        - Workshop Exercises and Case Studies
    - Final HIA Presentations with Clients:
        sections:
        - Presentation of Final HIA Results and Recommendations to Clients
        - Collaborating with Stakeholders for Effective Implementation of HIA Recommendations
        - Evaluating the Impact of HIA on Policy and Planning Processes