textbook:
  Environmental Technologies in Buildings: A Comprehensive Guide
  chapters:
    - Energy Use in Buildings:
        sections:
        - Understanding Climate: Solar Radiation
        - Where Is the Sun?
        - DIVA Shading Study (DIVA-GH2)
    - Thermal Comfort:
        sections:
        - CBE Comfort Tool
        - Case Studies
    - Active Solar:
        sections:
        - DIVA Radiation Maps + ArchSim PV Simulations (DIVA-GH7)
    - Light and Human Vision:
        sections:
        - Photometry
    - Visual Comfort:
        sections:
        - Thermal Mass
        - Heat Flow I
        - Heat Flow II
        - Insulation Materials
        - Ventilation
    - HVAC for Large Buildings:
        sections:
        - AIA student presentations
    - Acoustics:
        sections:
        - Acoustics I
    - Final Project:
        sections:
        - Individual meetings with graduate student groups
        - Exam week: final project presentations
    - Other Topics:
        sections:
        - Understanding Climate: Wind, Temperature, and Relative Humidity
        - Climate File Game
        - Lighting Design Principles
        - Energy Use in Buildings
        - Active Solar
        - Visual Comfort
        - Thermal Mass
        - Heat Flow I
        - Heat Flow II
        - Insulation Materials
        - Ventilation
        - HVAC for Large Buildings
        - Acoustics I
        - Individual meetings with graduate student groups
        - Exam week: final project presentations