# null represents Python's None. Will be replaced with default in the code.
# basic_config:
data_dir: null
toc_dir: table_of_contents
output_dir: textbooks
textbook: null
log_level: INFO
num_processes: 1
process_num: 0
filter_existing_books: true
batch_size: 256
skip_validation: false
max_threads: null

# llm config
llm_provider: openai
llm_model_name: gpt-4-0613
temperature: 0.1
max_tokens_to_sample: 1024
top_k: 100

# sampling config
max_related_context_to_sample: 2000
max_prev_snippet_to_sample: 2000

# rag config
do_rag: true
rag_server_url: null
rag_username: null
rag_password: null

